# Generated by Django 3.1.3 on 2021-08-20 09:41

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('content_en', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('content_fr', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('posted_datetime', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Academic Question Answer',
                'verbose_name_plural': 'Academic Question Answers',
            },
        ),
        migrations.CreateModel(
            name='AcademicAnswerComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted_datetime', models.DateTimeField(auto_now_add=True)),
                ('content', ckeditor.fields.RichTextField()),
                ('content_en', ckeditor.fields.RichTextField(null=True)),
                ('content_fr', ckeditor.fields.RichTextField(null=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Academic Answer Comment',
                'verbose_name_plural': 'Academic Answer Comments',
            },
        ),
        migrations.CreateModel(
            name='AcademicQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted_datetime', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('title_en', models.CharField(max_length=100, null=True, unique=True)),
                ('title_fr', models.CharField(max_length=100, null=True, unique=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('content_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('content_fr', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('slug', models.SlugField(max_length=250)),
                ('slug_en', models.SlugField(max_length=250, null=True)),
                ('slug_fr', models.SlugField(max_length=250, null=True)),
            ],
            options={
                'verbose_name': 'Academic Question',
                'verbose_name_plural': 'Academic Questions',
            },
        ),
        migrations.CreateModel(
            name='AcademicQuestionComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted_datetime', models.DateTimeField(auto_now_add=True)),
                ('content', ckeditor.fields.RichTextField()),
                ('content_en', ckeditor.fields.RichTextField(null=True)),
                ('content_fr', ckeditor.fields.RichTextField(null=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Academic Question Comment',
                'verbose_name_plural': 'Academic Question Comments',
            },
        ),
        migrations.CreateModel(
            name='SchoolAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('content_en', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('content_fr', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('posted_datetime', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'School Question Answer',
                'verbose_name_plural': 'School Question Answers',
            },
        ),
        migrations.CreateModel(
            name='SchoolAnswerComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted_datetime', models.DateTimeField(auto_now_add=True)),
                ('content', ckeditor.fields.RichTextField()),
                ('content_en', ckeditor.fields.RichTextField(null=True)),
                ('content_fr', ckeditor.fields.RichTextField(null=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'School Answer Comment',
                'verbose_name_plural': 'School Answer Comments',
            },
        ),
        migrations.CreateModel(
            name='SchoolQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted_datetime', models.DateTimeField(auto_now_add=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('content_en', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('content_fr', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
            ],
            options={
                'verbose_name': 'School Question',
                'verbose_name_plural': 'School Questions',
            },
        ),
        migrations.CreateModel(
            name='SchoolQuestionComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted_datetime', models.DateTimeField(auto_now_add=True)),
                ('content', ckeditor.fields.RichTextField()),
                ('content_en', ckeditor.fields.RichTextField(null=True)),
                ('content_fr', ckeditor.fields.RichTextField(null=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'School Question Comment',
                'verbose_name_plural': 'School Question Comments',
            },
        ),
        migrations.CreateModel(
            name='SchoolQuestionTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('name_en', models.CharField(max_length=30, null=True, unique=True)),
                ('name_fr', models.CharField(max_length=30, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('name_en', models.CharField(max_length=40, null=True, unique=True)),
                ('name_fr', models.CharField(max_length=40, null=True, unique=True)),
                ('slug', models.SlugField(max_length=200)),
                ('slug_en', models.SlugField(max_length=200, null=True)),
                ('slug_fr', models.SlugField(max_length=200, null=True)),
            ],
        ),
    ]
