# Generated by Django 3.1.3 on 2021-08-11 21:39

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('qa_site', '0002_auto_20210811_2137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicquestion',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='schoolquestion',
            name='tags',
        ),
        migrations.AddField(
            model_name='subject',
            name='topics',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
