# Generated by Django 3.1.3 on 2021-08-23 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa_site', '0002_auto_20210820_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicquestion',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='academicquestion',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='academicquestion',
            name='title_fr',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
