# Generated by Django 3.1.3 on 2021-10-18 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa_site', '0002_auto_20211017_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicquestiontag',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='academicquestiontag',
            name='name_en',
            field=models.CharField(max_length=20, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='academicquestiontag',
            name='name_fr',
            field=models.CharField(max_length=20, null=True, verbose_name='Name'),
        ),
    ]
