# Generated by Django 3.1.3 on 2021-08-26 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa_site', '0003_auto_20210823_0357'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='academicquestion',
            index=models.Index(fields=['-posted_datetime'], name='qa_site_aca_posted__2ed6b8_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolquestion',
            index=models.Index(fields=['-posted_datetime'], name='qa_site_sch_posted__39462b_idx'),
        ),
    ]
