# Generated by Django 3.1.3 on 2021-08-11 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qa_site', '0003_auto_20210811_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicquestion',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='academic_questions', related_query_name='academic_question', to='qa_site.subject'),
            preserve_default=False,
        ),
    ]
