# Generated by Django 3.1.3 on 2021-08-11 22:07

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa_site', '0004_academicquestion_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicanswer',
            name='content_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='academicanswer',
            name='content_fr',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='academicanswercomment',
            name='content_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='academicanswercomment',
            name='content_fr',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='academicquestion',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='academicquestion',
            name='content_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='academicquestion',
            name='content_fr',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='academicquestion',
            name='slug_en',
            field=models.SlugField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='academicquestion',
            name='slug_fr',
            field=models.SlugField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='academicquestion',
            name='title_en',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='academicquestion',
            name='title_fr',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='academicquestioncomment',
            name='content_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='academicquestioncomment',
            name='content_fr',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='schoolanswer',
            name='content_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='schoolanswer',
            name='content_fr',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='schoolanswercomment',
            name='content_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='schoolanswercomment',
            name='content_fr',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='schoolquestion',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schoolquestion',
            name='content_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='schoolquestion',
            name='content_fr',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='schoolquestion',
            name='slug_en',
            field=models.SlugField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='schoolquestion',
            name='slug_fr',
            field=models.SlugField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='schoolquestion',
            name='title_en',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='schoolquestion',
            name='title_fr',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='schoolquestioncomment',
            name='content_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='schoolquestioncomment',
            name='content_fr',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
