# Generated by Django 3.1.3 on 2021-08-30 00:14

import core.model_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa_site', '0004_auto_20210826_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=core.model_fields.FullNameField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name_en',
            field=core.model_fields.FullNameField(max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name_fr',
            field=core.model_fields.FullNameField(max_length=30, null=True, unique=True),
        ),
    ]
