# Generated by Django 3.1.3 on 2021-11-01 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa_site', '0004_auto_20211018_0326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicquestion',
            name='title',
            field=models.CharField(max_length=150, unique=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='academicquestion',
            name='title_en',
            field=models.CharField(max_length=150, null=True, unique=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='academicquestion',
            name='title_fr',
            field=models.CharField(max_length=150, null=True, unique=True, verbose_name='Title'),
        ),
    ]
