# Generated by Django 3.1.3 on 2021-08-31 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa_site', '0005_auto_20210830_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolquestiontag',
            name='slug',
            field=models.SlugField(default='def-slug', max_length=100),
            preserve_default=False,
        ),
    ]
