# Generated by Django 3.1.3 on 2021-08-11 23:38

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('qa_site', '0005_auto_20210811_2207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='topics',
        ),
        migrations.AddField(
            model_name='academicquestion',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='schoolquestion',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='subject',
            name='name_en',
            field=models.CharField(max_length=40, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='name_fr',
            field=models.CharField(max_length=40, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='slug_en',
            field=models.SlugField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='slug_fr',
            field=models.SlugField(max_length=200, null=True),
        ),
    ]
