# Generated by Django 3.1.3 on 2021-08-31 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa_site', '0006_schoolquestiontag_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolquestiontag',
            name='slug_en',
            field=models.SlugField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='schoolquestiontag',
            name='slug_fr',
            field=models.SlugField(max_length=100, null=True),
        ),
    ]
