# Generated by Django 3.1.3 on 2021-08-12 14:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qa_site', '0007_auto_20210812_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicquestion',
            name='bookmarkers',
            field=models.ManyToManyField(blank=True, related_name='bookmarked_academic_questions', related_query_name='bookmarked_academic_question', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='academicquestion',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='following_academic_questions', related_query_name='following_academic_question', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='schoolquestion',
            name='bookmarkers',
            field=models.ManyToManyField(blank=True, related_name='bookmarked_school_questions', related_query_name='bookmarked_school_question', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='schoolquestion',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='following_school_questions', related_query_name='following_school_question', to=settings.AUTH_USER_MODEL),
        ),
    ]
