# Generated by Django 3.1.3 on 2021-08-31 23:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('qa_site', '0007_auto_20210831_1941'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoolquestiontag',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='schoolquestiontag',
            name='datetime_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='schoolquestiontag',
            index=models.Index(fields=['name'], name='qa_site_sch_name_4e12bb_idx'),
        ),
    ]
