# Generated by Django 3.1.3 on 2021-09-01 02:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('qa_site', '0008_auto_20210831_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='datetime_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
