# Generated by Django 3.1.3 on 2021-09-08 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa_site', '0009_subject_datetime_added'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicquestion',
            options={'ordering': ['-posted_datetime'], 'verbose_name': 'Academic Question', 'verbose_name_plural': 'Academic Questions'},
        ),
        migrations.AlterModelOptions(
            name='schoolquestion',
            options={'ordering': ['-posted_datetime'], 'verbose_name': 'School Question', 'verbose_name_plural': 'School Questions'},
        ),
    ]
