# Generated by Django 3.1.3 on 2021-09-10 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa_site', '0010_auto_20210908_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicquestion',
            name='title',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='academicquestion',
            name='title_en',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='academicquestion',
            name='title_fr',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
