# Generated by Django 3.1.3 on 2021-08-14 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa_site', '0010_auto_20210814_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicanswer',
            name='downvote_count',
        ),
        migrations.RemoveField(
            model_name='academicanswer',
            name='upvote_count',
        ),
        migrations.RemoveField(
            model_name='academicquestion',
            name='downvote_count',
        ),
        migrations.RemoveField(
            model_name='academicquestion',
            name='upvote_count',
        ),
        migrations.RemoveField(
            model_name='schoolanswer',
            name='downvote_count',
        ),
        migrations.RemoveField(
            model_name='schoolanswer',
            name='upvote_count',
        ),
        migrations.RemoveField(
            model_name='schoolquestion',
            name='downvote_count',
        ),
        migrations.RemoveField(
            model_name='schoolquestion',
            name='upvote_count',
        ),
    ]
