# Generated by Django 3.1.3 on 2021-08-14 18:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qa_site', '0011_auto_20210814_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicanswercomment',
            name='vote_count',
        ),
        migrations.RemoveField(
            model_name='academicquestioncomment',
            name='vote_count',
        ),
        migrations.RemoveField(
            model_name='schoolanswercomment',
            name='vote_count',
        ),
        migrations.RemoveField(
            model_name='schoolquestioncomment',
            name='vote_count',
        ),
        migrations.AddField(
            model_name='academicanswercomment',
            name='upvoters',
            field=models.ManyToManyField(blank=True, related_name='upvoted_academic_answer_comments', related_query_name='upvoted_academic_answer_comment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='academicquestioncomment',
            name='upvoters',
            field=models.ManyToManyField(blank=True, related_name='upvoted_academic_question_comments', related_query_name='upvoted_academic_question_comment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schoolanswercomment',
            name='upvoters',
            field=models.ManyToManyField(blank=True, related_name='upvoted_school_answer_comments', related_query_name='upvoted_school_answer_comment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schoolquestioncomment',
            name='upvoters',
            field=models.ManyToManyField(blank=True, related_name='upvoted_school_question_comments', related_query_name='upvoted_school_question_comment', to=settings.AUTH_USER_MODEL),
        ),
    ]
