# Generated by Django 3.1.3 on 2021-09-17 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa_site', '0012_auto_20210917_1410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicanswer',
            name='downvote_count',
        ),
        migrations.RemoveField(
            model_name='academicanswer',
            name='upvote_count',
        ),
        migrations.RemoveField(
            model_name='academicquestion',
            name='bookmark_count',
        ),
        migrations.RemoveField(
            model_name='academicquestion',
            name='downvote_count',
        ),
        migrations.RemoveField(
            model_name='academicquestion',
            name='num_answers',
        ),
        migrations.RemoveField(
            model_name='academicquestion',
            name='num_followers',
        ),
        migrations.RemoveField(
            model_name='academicquestion',
            name='upvote_count',
        ),
        migrations.RemoveField(
            model_name='schoolanswer',
            name='downvote_count',
        ),
        migrations.RemoveField(
            model_name='schoolanswer',
            name='upvote_count',
        ),
        migrations.RemoveField(
            model_name='schoolquestion',
            name='bookmark_count',
        ),
        migrations.RemoveField(
            model_name='schoolquestion',
            name='downvote_count',
        ),
        migrations.RemoveField(
            model_name='schoolquestion',
            name='num_answers',
        ),
        migrations.RemoveField(
            model_name='schoolquestion',
            name='num_followers',
        ),
        migrations.RemoveField(
            model_name='schoolquestion',
            name='upvote_count',
        ),
    ]
