# Generated by Django 3.1.3 on 2021-09-18 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qa_site', '0013_auto_20210917_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicquestion',
            name='subject',
            field=models.ForeignKey(blank=True, help_text='Allow empty if your subject is not present.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='academic_questions', related_query_name='academic_question', to='qa_site.subject'),
        ),
    ]
