# Generated by Django 3.1.3 on 2021-09-25 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa_site', '0015_auto_20210925_0531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicanswer',
            name='original_language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French')], max_length=2),
        ),
        migrations.AlterField(
            model_name='academicanswercomment',
            name='original_language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French')], max_length=2),
        ),
        migrations.AlterField(
            model_name='academicquestion',
            name='original_language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French')], max_length=2),
        ),
        migrations.AlterField(
            model_name='academicquestioncomment',
            name='original_language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French')], max_length=2),
        ),
        migrations.AlterField(
            model_name='schoolanswer',
            name='original_language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French')], max_length=2),
        ),
        migrations.AlterField(
            model_name='schoolanswercomment',
            name='original_language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French')], max_length=2),
        ),
        migrations.AlterField(
            model_name='schoolquestion',
            name='original_language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French')], max_length=2),
        ),
        migrations.AlterField(
            model_name='schoolquestioncomment',
            name='original_language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French')], max_length=2),
        ),
    ]
