# Generated by Django 3.1.3 on 2021-09-28 20:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qa_site', '0017_auto_20210925_0538'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicanswercomment',
            name='users_mentioned',
            field=models.ManyToManyField(blank=True, related_name='_academicanswercomment_users_mentioned_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='academicquestioncomment',
            name='users_mentioned',
            field=models.ManyToManyField(blank=True, related_name='_academicquestioncomment_users_mentioned_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schoolanswercomment',
            name='users_mentioned',
            field=models.ManyToManyField(blank=True, related_name='_schoolanswercomment_users_mentioned_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schoolquestioncomment',
            name='users_mentioned',
            field=models.ManyToManyField(blank=True, related_name='_schoolquestioncomment_users_mentioned_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
