# Generated by Django 3.1.3 on 2021-09-30 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa_site', '0018_auto_20210928_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
