# Generated by Django 3.1.3 on 2021-10-02 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_institution'),
        ('qa_site', '0019_subject_last_modified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolquestion',
            name='tags',
        ),
        migrations.AddField(
            model_name='academicquestion',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='schoolquestion',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='schoolquestion',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', related_query_name='question', to='core.institution'),
        ),
        migrations.DeleteModel(
            name='SchoolQuestionTag',
        ),
    ]
