# Generated by Django 3.1.3 on 2021-10-06 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qa_site', '0020_auto_20211002_1828'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicQuestionTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Academic Question Tag',
                'verbose_name_plural': 'Academic Question Tags',
            },
        ),
        migrations.RemoveField(
            model_name='academicquestion',
            name='tags',
        ),
        migrations.CreateModel(
            name='TaggedAcademicQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_questions', to='qa_site.academicquestiontag')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
