# Generated by Django 3.1.3 on 2021-10-06 05:21

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('qa_site', '0021_auto_20211006_0518'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicquestion',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='qa_site.TaggedAcademicQuestion', to='qa_site.AcademicQuestionTag', verbose_name='Tags'),
        ),
    ]
