# Generated by Django 3.1.3 on 2021-10-06 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa_site', '0022_academicquestion_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicquestiontag',
            name='name_en',
            field=models.CharField(max_length=20, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='academicquestiontag',
            name='name_fr',
            field=models.CharField(max_length=20, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='academicquestiontag',
            name='slug_en',
            field=models.SlugField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='academicquestiontag',
            name='slug_fr',
            field=models.SlugField(max_length=100, null=True, unique=True),
        ),
    ]
