# Generated by Django 3.1.3 on 2021-10-07 01:28

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qa_site', '0023_auto_20211006_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicanswercomment',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='academicanswercomment',
            name='content_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='academicanswercomment',
            name='content_fr',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='academicquestion',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='academicquestion',
            name='content_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='academicquestion',
            name='content_fr',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='academicquestion',
            name='subject',
            field=models.ForeignKey(blank=True, help_text='Allow this field empty if your subject is not present.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='academic_questions', related_query_name='academic_question', to='qa_site.subject', verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='academicquestion',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='academicquestion',
            name='title_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='academicquestion',
            name='title_fr',
            field=models.CharField(max_length=150, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='academicquestioncomment',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='academicquestioncomment',
            name='content_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='academicquestioncomment',
            name='content_fr',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='schoolanswercomment',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='schoolanswercomment',
            name='content_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='schoolanswercomment',
            name='content_fr',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='schoolquestioncomment',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='schoolquestioncomment',
            name='content_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='schoolquestioncomment',
            name='content_fr',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name_en',
            field=models.CharField(max_length=30, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name_fr',
            field=models.CharField(max_length=30, null=True, unique=True, verbose_name='Name'),
        ),
    ]
