# Generated by Django 3.1.3 on 2021-10-07 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qa_site', '0024_auto_20211007_0128'),
    ]

    operations = [
        migrations.AddField(
            model_name='taggedacademicquestion',
            name='content_object',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='qa_site.academicquestion'),
            preserve_default=False,
        ),
    ]
