# Generated by Django 3.1.3 on 2021-10-17 22:43

import core.model_fields
import core.validators
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', core.model_fields.NormalizedEmailField(error_messages={'unique': 'A user with that email already exists.'}, help_text='We will send a verification code to this email', max_length=50, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='Email address')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Your username should be between 4 to 15 characters and the first 4 characters must be letters. <br> It should not contain any symbols, dashes or spaces. <br>All other characters are allowed (letters, numbers, hyphens and underscores).', max_length=15, unique=True, validators=[core.validators.UsernameValidator()], verbose_name='Username')),
                ('full_name', models.CharField(help_text='Enter a valid full name. It should be two or three of your names separated by a space and each name may contain only letters or hyphens. <br>No name should start or end with a hyphen, and no name should contain only hyphens.', max_length=25, validators=[core.validators.FullNameValidator()], verbose_name='Full name')),
                ('first_language', models.CharField(choices=[('en', 'English'), ('fr', 'French')], default='en', help_text="Your preferred language. Don't worry, you can always view the site in another language.", max_length=3, verbose_name='First language')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=2, verbose_name='Gender')),
                ('site_points', models.PositiveIntegerField(default=10, editable=False, verbose_name='Site points')),
                ('deactivation_datetime', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Deactivation date/time')),
                ('datetime_joined', models.DateTimeField(auto_now_add=True, verbose_name='Date/time joined')),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_mod', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(choices=[('MTN', 'MTN'), ('Nexttel', 'Nexttel'), ('Orange', 'Orange'), ('CAMTEL', 'CAMTEL'), ('O', 'Other')], default='MTN', max_length=8, verbose_name='Operator')),
                ('number', models.CharField(help_text='Enter mobile number <b>(without +237)</b>', max_length=20, verbose_name='Phone number')),
                ('can_whatsapp', models.BooleanField(default=False, verbose_name='Works with WhatsApp')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', related_query_name='phone_number', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Phone Number',
                'verbose_name_plural': 'Phone Numbers',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['-site_points'], name='users_user_site_po_4a5979_idx'),
        ),
    ]
