# Generated by Django 3.2 on 2022-07-18 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20220718_2220'),
        ('users', '0002_auto_20220714_0425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonenumber',
            name='operator',
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='users', related_query_name='user', to='core.country', verbose_name='Country of residence'),
        ),
    ]
