# Generated by Django 3.2 on 2022-08-11 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_phonenumber_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='full_name',
        ),
    ]
