# Generated by Django 3.2 on 2022-10-01 07:07

import core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_user_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_changed_username_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Your username should be between 4 to 15 characters and the first 4 characters must be letters. <br> It should not contain any symbols, dashes or spaces. <br>All other characters are allowed (letters, numbers, hyphens and underscores). <br>Also, your username cannot be changed until after 15 days from the last time you changed it. ', max_length=15, unique=True, validators=[core.validators.UsernameValidator()], verbose_name='Username'),
        ),
    ]
