# Generated by Django 3.1.3 on 2021-11-14 07:46

import core.fields
import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageHolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', core.fields.DynamicStorageImageField(upload_to='temporal_photos/')),
            ],
            bases=(models.Model, core.utils.PhotoModelMixin),
        ),
    ]
