# Generated by Django 3.1.3 on 2021-11-25 00:28

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20211125_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageholder',
            name='height',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imageholder',
            name='width',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imageholder',
            name='file',
            field=core.fields.DynamicStorageImageField(height_field='height', upload_to='temporal_photos/', width_field='width'),
        ),
    ]
