# Generated by Django 3.2 on 2022-07-18 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20220718_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='institutions', related_query_name='institution', to='core.country', verbose_name='Country'),
            preserve_default=False,
        ),
    ]
