# Generated by Django 3.2 on 2022-07-24 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_city'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'Cities'},
        ),
    ]
