# Generated by Django 3.2 on 2022-12-04 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20220724_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='currency',
            field=models.CharField(default='$', max_length=3),
            preserve_default=False,
        ),
    ]
