# Generated by Django 3.1.3 on 2021-08-17 00:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketplace', '0026_auto_20210811_0028'),
    ]

    operations = [
        migrations.CreateModel(
            name='PastPaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('title_en', models.CharField(blank=True, max_length=255, null=True)),
                ('title_fr', models.CharField(blank=True, max_length=255, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='past_papers/')),
                ('posted_datetime', models.DateTimeField(auto_now_add=True)),
                ('written_date', models.DateField(blank=True, null=True)),
                ('poster', models.ForeignKey(on_delete=models.SET(users.models.get_dummy_user), related_name='past_papers', related_query_name='past_paper', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='papers', related_query_name='paper', to='marketplace.institution')),
            ],
        ),
        migrations.CreateModel(
            name='PastPaperPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('upload_datetime', models.DateTimeField(auto_now_add=True)),
                ('file', models.ImageField(upload_to='past_paper_photos/')),
                ('past_paper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', related_query_name='photo', to='past_papers.pastpaper')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
