# Generated by Django 3.1.3 on 2021-08-20 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PastPaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('L1', 'Level 1'), ('L2', 'Level 2'), ('L3', 'Level 3'), ('L4', 'Level 5'), ('M', 'Masters'), ('PhD', 'Doctorate'), ('Other', 'Other')], max_length=7)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='past_papers/')),
                ('posted_datetime', models.DateTimeField(auto_now_add=True)),
                ('written_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PastPaperPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('upload_datetime', models.DateTimeField(auto_now_add=True)),
                ('file', models.ImageField(upload_to='past_paper_photos/')),
                ('past_paper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', related_query_name='photo', to='past_papers.pastpaper')),
            ],
        ),
    ]
