# Generated by Django 3.1.3 on 2021-08-17 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0026_auto_20210811_0028'),
        ('qa_site', '0012_auto_20210814_1846'),
        ('past_papers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastpaper',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='past_papers', related_query_name='past_paper', to='qa_site.subject'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pastpaper',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='past_papers', related_query_name='past_paper', to='marketplace.institution'),
        ),
    ]
