# Generated by Django 3.1.3 on 2021-08-20 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('past_papers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketplace', '0002_auto_20210820_0941'),
        ('qa_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastpaper',
            name='poster',
            field=models.ForeignKey(on_delete=models.SET(users.models.get_dummy_user), related_name='past_papers', related_query_name='past_paper', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pastpaper',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='past_papers', related_query_name='past_paper', to='marketplace.institution'),
        ),
        migrations.AddField(
            model_name='pastpaper',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='past_papers', related_query_name='past_paper', to='qa_site.subject'),
        ),
    ]
