# Generated by Django 3.1.3 on 2021-08-26 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('past_papers', '0002_auto_20210820_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastpaper',
            name='level',
            field=models.CharField(choices=[('PRI', 'Primary'), ('SEC', 'Secondary'), ('HS', 'High school'), ('BACH', "HND/Bachelor's"), ('MS', "Master's"), ('PhD', 'Doctorate')], max_length=5, verbose_name='Educational level'),
        ),
    ]
