# Generated by Django 3.1.3 on 2021-08-27 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('past_papers', '0003_auto_20210826_2305'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='pastpaper',
            index=models.Index(fields=['-posted_datetime'], name='past_papers_posted__3269e7_idx'),
        ),
    ]
