# Generated by Django 3.1.3 on 2021-11-02 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('past_papers', '0003_auto_20211101_0400'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='original_language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French')], default='en', editable=False, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='update_language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('fr', 'French')], editable=False, max_length=2),
        ),
    ]
