# Generated by Django 3.1.3 on 2021-08-17 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qa_site', '0012_auto_20210814_1846'),
        ('past_papers', '0003_auto_20210817_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastpaper',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='past_papers', related_query_name='past_paper', to='qa_site.subject'),
        ),
    ]
