# Generated by Django 3.1.3 on 2021-08-17 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('past_papers', '0004_auto_20210817_0653'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastpaper',
            name='level',
            field=models.CharField(choices=[('L1', 'Level 1'), ('L2', 'Level 2'), ('L3', 'Level 3'), ('L4', 'Level 5'), ('M1', 'Master 1'), ('M2', 'Master 2'), ('PhD', 'Doctorate'), ('Other', 'Other')], default='Other', max_length=7),
        ),
    ]
