# Generated by Django 3.1.3 on 2021-08-27 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('past_papers', '0004_auto_20210827_0152'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastpaper',
            name='default_language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French')], default='en', max_length=2),
        ),
        migrations.AddField(
            model_name='pastpaper',
            name='slug',
            field=models.SlugField(default=2, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pastpaper',
            name='level',
            field=models.CharField(choices=[('PRI', 'Primary'), ('SEC', 'Secondary'), ('HS', 'High school'), ('BACH', "HND/Bachelor's"), ('MS', "Master's"), ('PhD', 'Doctorate')], max_length=5),
        ),
        migrations.AlterField(
            model_name='pastpaper',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
