# Generated by Django 3.1.3 on 2021-11-13 09:31

import core.model_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('past_papers', '0005_auto_20211113_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastpaperphoto',
            name='file',
            field=core.model_fields.DynamicStorageImageField(upload_to='past_paper_photos/'),
        ),
    ]
