# Generated by Django 3.1.3 on 2021-08-28 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('past_papers', '0005_auto_20210827_0339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pastpaperphoto',
            name='title',
        ),
        migrations.AlterField(
            model_name='pastpaper',
            name='level',
            field=models.CharField(choices=[('PRI', 'Primary School'), ('SEC', 'Secondary School'), ('HS', 'High School'), ('BACH', "HND/Bachelor's"), ('MS', "Master's"), ('PhD', 'Doctorate')], max_length=5),
        ),
        migrations.AlterField(
            model_name='pastpaper',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
