# Generated by Django 3.1.3 on 2021-08-28 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('past_papers', '0006_auto_20210828_0345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pastpaperphoto',
            name='past_paper',
        ),
        migrations.RemoveField(
            model_name='pastpaperphoto',
            name='upload_datetime',
        ),
        migrations.AlterField(
            model_name='pastpaper',
            name='file',
            field=models.FileField(blank=True, default='', upload_to='past_papers/'),
            preserve_default=False,
        ),
    ]
