# Generated by Django 3.1.3 on 2021-08-17 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('past_papers', '0006_auto_20210817_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastpaper',
            name='title',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pastpaper',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pastpaper',
            name='title_fr',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
