# Generated by Django 3.1.3 on 2021-08-29 01:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qa_site', '0004_auto_20210826_1642'),
        ('past_papers', '0007_auto_20210828_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastpaper',
            name='type',
            field=models.CharField(choices=[('COMM', 'Commercial'), ('GEN', 'General'), ('TECH', 'Technical')], default='GEN', max_length=5),
        ),
        migrations.AlterField(
            model_name='pastpaper',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='past_papers', related_query_name='past_paper', to='qa_site.subject'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('posted_datetime', models.DateTimeField(auto_now_add=True)),
                ('past_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', related_query_name='comment', to='past_papers.pastpaper')),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='past_paper_comments', related_query_name='past_paper_comment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['-posted_datetime'], name='past_papers_posted__90d67f_idx'),
        ),
    ]
