# Generated by Django 3.1.3 on 2021-08-30 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('past_papers', '0008_auto_20210829_0134'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-posted_datetime']},
        ),
        migrations.AlterModelOptions(
            name='pastpaper',
            options={'ordering': ['-posted_datetime']},
        ),
        migrations.AlterField(
            model_name='pastpaper',
            name='level',
            field=models.CharField(choices=[('O', 'Ordinary Level'), ('A', 'Advanced Level'), ('BEPC', 'BEPC'), ('PROB', 'Probatoire'), ('BAC', 'Baccalaureat'), ('BACH', "HND/Bachelor's"), ('BTS', 'BTS'), ('MS', "Master's"), ('PhD', 'Doctorate')], max_length=5),
        ),
    ]
