# Generated by Django 3.1.3 on 2021-08-18 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('past_papers', '0008_auto_20210818_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastpaper',
            name='level',
            field=models.CharField(choices=[('L1', 'Level 1'), ('L2', 'Level 2'), ('L3', 'Level 3'), ('L4', 'Level 5'), ('M', 'Masters'), ('PhD', 'Doctorate'), ('Other', 'Other')], max_length=7),
        ),
    ]
