# Generated by Django 3.1.3 on 2021-08-30 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('past_papers', '0009_auto_20210830_0014'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pastpaper',
            options={},
        ),
    ]
