# Generated by Django 3.1.3 on 2021-11-25 01:11

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('past_papers', '0009_auto_20211124_2345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pastpaperphoto',
            name='height',
        ),
        migrations.RemoveField(
            model_name='pastpaperphoto',
            name='width',
        ),
        migrations.AlterField(
            model_name='pastpaperphoto',
            name='file',
            field=easy_thumbnails.fields.ThumbnailerImageField(upload_to='past_paper_photos/'),
        ),
    ]
