# Generated by Django 3.1.3 on 2021-09-01 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('past_papers', '0010_auto_20210830_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastpaper',
            name='level',
            field=models.CharField(choices=[('O', 'Ordinary Level'), ('A', 'Advanced Level'), ('BEPC', 'BEPC'), ('PROB', 'Probatoire'), ('BAC', 'Baccalaureat'), ('BACH', "HND/Bachelor's"), ('BTS', 'BTS'), ('LIC', 'Licence'), ('MS', "Master's"), ('PhD', 'Doctorate')], max_length=5),
        ),
    ]
