# Generated by Django 3.1.3 on 2021-09-12 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qa_site', '0011_auto_20210910_0631'),
        ('past_papers', '0012_auto_20210910_0345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastpaper',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='past_papers', related_query_name='past_paper', to='qa_site.subject'),
        ),
    ]
