# Generated by Django 3.1.3 on 2021-09-25 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('past_papers', '0014_pastpaperphoto_upload_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='pastpaper',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
