# Generated by Django 3.1.3 on 2021-10-02 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_institution'),
        ('past_papers', '0015_auto_20210925_0531'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastpaper',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pastpaper',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='past_papers', related_query_name='past_paper', to='core.institution'),
        ),
    ]
