# Generated by Django 3.1.3 on 2021-10-13 18:25

import core.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('past_papers', '0018_pastpaper_bookmarkers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastpaperphoto',
            name='file',
            field=models.ImageField(storage=core.storage_backends.PublicMediaStorage(), upload_to='past_paper_photos/'),
        ),
    ]
