# Generated by Django 3.1.3 on 2021-10-14 01:36

import core.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('past_papers', '0019_auto_20211013_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastpaper',
            name='file',
            field=models.FileField(blank=True, storage=core.storage_backends.PublicMediaStorage(), upload_to='past_papers/'),
        ),
    ]
