# Generated by Django 3.2 on 2022-07-18 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0014_auto_20220718_2154'),
        ('requested_items', '0010_auto_20220714_0425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requesteditem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='requested_items', related_query_name='requested_item', to='marketplace.itemcategory', verbose_name='Category'),
        ),
    ]
