# Generated by Django 3.2 on 2022-09-28 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('requested_items', '0014_auto_20220928_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestedItemBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookmark_datetime', models.DateTimeField(auto_now_add=True)),
                ('bookmarker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('requested_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='requested_items.requesteditem')),
            ],
        ),
        migrations.AddField(
            model_name='requesteditem',
            name='bookmarkers',
            field=models.ManyToManyField(blank=True, related_name='bookmarked_requested_items', related_query_name='bookmarked_requested_item', through='requested_items.RequestedItemBookmark', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='requesteditembookmark',
            constraint=models.UniqueConstraint(fields=('requested_item', 'bookmarker'), name='unique_requested_item_bookmark'),
        ),
    ]
