# Generated by Django 3.2 on 2022-09-28 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requested_items', '0015_auto_20220928_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requesteditem',
            name='item_requested',
            field=models.CharField(help_text='What item do you need?', max_length=100, verbose_name='Item requested'),
        ),
        migrations.AlterField(
            model_name='requesteditem',
            name='item_requested_en',
            field=models.CharField(help_text='What item do you need?', max_length=100, null=True, verbose_name='Item requested'),
        ),
        migrations.AlterField(
            model_name='requesteditem',
            name='item_requested_fr',
            field=models.CharField(help_text='What item do you need?', max_length=100, null=True, verbose_name='Item requested'),
        ),
    ]
