# Generated by Django 3.1.3 on 2021-09-01 20:55

import core.model_fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketplace', '0011_auto_20210901_2053'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_auto_20210828_1947'),
    ]

    operations = [
        migrations.CreateModel(
            name='LostItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_lost', models.CharField(help_text='What have you lost', max_length=50)),
                ('slug', models.SlugField(max_length=250)),
                ('area_lost', models.CharField(help_text='Where you think you lost the item', max_length=100)),
                ('how_lost', models.TextField(default='Good day, ', help_text='Explain how you think you lost the item, stating areas you passed across')),
                ('posted_datetime', models.DateTimeField(auto_now_add=True)),
                ('contact_email', core.model_fields.NormalizedEmailField(help_text='Email address to contact; enter a valid email.', max_length=50, validators=[django.core.validators.EmailValidator()], verbose_name='Email address')),
                ('contact_numbers', models.ManyToManyField(related_name='_lostitem_contact_numbers_+', to='users.PhoneNumber')),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lost_items', related_query_name='lost_item', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lost_items', related_query_name='lost_item', to='marketplace.institution')),
            ],
        ),
        migrations.CreateModel(
            name='FoundItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_found', models.CharField(help_text='What have you found', max_length=50)),
                ('slug', models.SlugField(max_length=250)),
                ('area_found', models.CharField(help_text='Where did you find the item', max_length=100)),
                ('extra_info', models.TextField(help_text='Extra information about how you found the item')),
                ('posted_datetime', models.DateTimeField(auto_now_add=True)),
                ('contact_email', core.model_fields.NormalizedEmailField(help_text='Email address to contact; enter a valid email.', max_length=50, validators=[django.core.validators.EmailValidator()], verbose_name='Email address')),
                ('contact_numbers', models.ManyToManyField(related_name='_founditem_contact_numbers_+', to='users.PhoneNumber')),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='found_items', related_query_name='found_item', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='found_items', related_query_name='found_item', to='marketplace.institution')),
            ],
        ),
    ]
