# Generated by Django 3.1.3 on 2021-09-01 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost_and_found', '0002_auto_20210901_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='founditem',
            name='area_found_en',
            field=models.CharField(help_text='Where did you find the item', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='founditem',
            name='area_found_fr',
            field=models.CharField(help_text='Where did you find the item', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='founditem',
            name='extra_info_en',
            field=models.TextField(help_text='Extra information about how you found the item', null=True),
        ),
        migrations.AddField(
            model_name='founditem',
            name='extra_info_fr',
            field=models.TextField(help_text='Extra information about how you found the item', null=True),
        ),
        migrations.AddField(
            model_name='founditem',
            name='item_found_en',
            field=models.CharField(help_text='What have you found', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='founditem',
            name='item_found_fr',
            field=models.CharField(help_text='What have you found', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='founditem',
            name='slug_en',
            field=models.SlugField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='founditem',
            name='slug_fr',
            field=models.SlugField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='lostitem',
            name='area_lost_en',
            field=models.CharField(help_text='Where you think you lost the item', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lostitem',
            name='area_lost_fr',
            field=models.CharField(help_text='Where you think you lost the item', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lostitem',
            name='how_lost_en',
            field=models.TextField(default='Good day, ', help_text='Explain how you think you lost the item, stating areas you passed across', null=True),
        ),
        migrations.AddField(
            model_name='lostitem',
            name='how_lost_fr',
            field=models.TextField(default='Good day, ', help_text='Explain how you think you lost the item, stating areas you passed across', null=True),
        ),
        migrations.AddField(
            model_name='lostitem',
            name='item_lost_en',
            field=models.CharField(help_text='What have you lost', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lostitem',
            name='item_lost_fr',
            field=models.CharField(help_text='What have you lost', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lostitem',
            name='slug_en',
            field=models.SlugField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='lostitem',
            name='slug_fr',
            field=models.SlugField(max_length=250, null=True),
        ),
    ]
