# Generated by Django 3.1.3 on 2021-09-01 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost_and_found', '0004_auto_20210901_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='founditem',
            name='extra_info',
        ),
        migrations.RemoveField(
            model_name='founditem',
            name='extra_info_en',
        ),
        migrations.RemoveField(
            model_name='founditem',
            name='extra_info_fr',
        ),
        migrations.AddField(
            model_name='founditem',
            name='how_found',
            field=models.TextField(default='adf', help_text='Explain how you found the item'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='founditem',
            name='how_found_en',
            field=models.TextField(help_text='Explain how you found the item', null=True),
        ),
        migrations.AddField(
            model_name='founditem',
            name='how_found_fr',
            field=models.TextField(help_text='Explain how you found the item', null=True),
        ),
    ]
