# Generated by Django 3.1.3 on 2021-09-02 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost_and_found', '0005_auto_20210901_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='founditem',
            name='contact_name',
            field=models.CharField(default='saf', help_text='Please use your real names.', max_length=25, verbose_name='Full name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lostitem',
            name='bounty',
            field=models.CharField(blank=True, help_text='Award/bounty given to the person who will return the item. Make sure that you are in possession of the award. <br> This is optional but can be used as motivation.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lostitem',
            name='bounty_en',
            field=models.CharField(blank=True, help_text='Award/bounty given to the person who will return the item. Make sure that you are in possession of the award. <br> This is optional but can be used as motivation.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lostitem',
            name='bounty_fr',
            field=models.CharField(blank=True, help_text='Award/bounty given to the person who will return the item. Make sure that you are in possession of the award. <br> This is optional but can be used as motivation.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lostitem',
            name='contact_name',
            field=models.CharField(default='dasf', help_text='Please use your real names.', max_length=25, verbose_name='Full name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lostitem',
            name='item_description',
            field=models.TextField(default='desc', help_text='Describe the lost item stating the important aspects.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lostitem',
            name='item_description_en',
            field=models.TextField(help_text='Describe the lost item stating the important aspects.', null=True),
        ),
        migrations.AddField(
            model_name='lostitem',
            name='item_description_fr',
            field=models.TextField(help_text='Describe the lost item stating the important aspects.', null=True),
        ),
        migrations.AlterField(
            model_name='founditem',
            name='slug',
            field=models.SlugField(max_length=100),
        ),
        migrations.AlterField(
            model_name='founditem',
            name='slug_en',
            field=models.SlugField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='founditem',
            name='slug_fr',
            field=models.SlugField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='how_lost',
            field=models.TextField(default='Good day, ', help_text='Explain how you think you lost the item, stating areas you passed across or visited'),
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='how_lost_en',
            field=models.TextField(default='Good day, ', help_text='Explain how you think you lost the item, stating areas you passed across or visited', null=True),
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='how_lost_fr',
            field=models.TextField(default='Good day, ', help_text='Explain how you think you lost the item, stating areas you passed across or visited', null=True),
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='slug',
            field=models.SlugField(max_length=100),
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='slug_en',
            field=models.SlugField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='slug_fr',
            field=models.SlugField(max_length=100, null=True),
        ),
    ]
