# Generated by Django 3.1.3 on 2021-09-02 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost_and_found', '0008_auto_20210902_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostitem',
            name='item_description',
            field=models.TextField(help_text='Describe the lost item stating its important aspects.'),
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='item_description_en',
            field=models.TextField(help_text='Describe the lost item stating its important aspects.', null=True),
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='item_description_fr',
            field=models.TextField(help_text='Describe the lost item stating its important aspects.', null=True),
        ),
    ]
