# Generated by Django 3.1.3 on 2021-09-10 03:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lost_and_found', '0009_auto_20210902_2212'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='founditem',
            options={'ordering': ['-posted_datetime']},
        ),
        migrations.AlterModelOptions(
            name='lostitem',
            options={'ordering': ['-posted_datetime']},
        ),
        migrations.AddField(
            model_name='founditem',
            name='expiry_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lostitem',
            name='expiry_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='founditem',
            index=models.Index(fields=['-posted_datetime'], name='lost_and_fo_posted__5efadc_idx'),
        ),
        migrations.AddIndex(
            model_name='lostitem',
            index=models.Index(fields=['-posted_datetime'], name='lost_and_fo_posted__ae3e94_idx'),
        ),
    ]
