# Generated by Django 3.1.3 on 2021-09-12 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lost_and_found', '0011_auto_20210910_0631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lostitemphoto',
            name='title',
        ),
    ]
