# Generated by Django 3.1.3 on 2021-09-25 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost_and_found', '0012_remove_lostitemphoto_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='founditem',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='lostitem',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
