# Generated by Django 3.1.3 on 2021-09-26 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lost_and_found', '0015_auto_20210925_0538'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lostitemphoto',
            options={'verbose_name': 'Lost Item Photo', 'verbose_name_plural': 'Lost Items Photos'},
        ),
        migrations.RemoveField(
            model_name='founditem',
            name='expiry_datetime',
        ),
        migrations.RemoveField(
            model_name='lostitem',
            name='expiry_datetime',
        ),
    ]
