# Generated by Django 3.1.3 on 2021-09-30 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost_and_found', '0016_auto_20210926_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='founditem',
            name='original_language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French')], editable=False, help_text='Language in which post was created', max_length=2),
        ),
        migrations.AlterField(
            model_name='founditem',
            name='slug',
            field=models.SlugField(max_length=255),
        ),
        migrations.AlterField(
            model_name='founditem',
            name='slug_en',
            field=models.SlugField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='founditem',
            name='slug_fr',
            field=models.SlugField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='original_language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French')], editable=False, help_text='Language in which post was created', max_length=2),
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='slug',
            field=models.SlugField(max_length=255),
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='slug_en',
            field=models.SlugField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='slug_fr',
            field=models.SlugField(max_length=255, null=True),
        ),
    ]
