# Generated by Django 3.1.3 on 2021-10-02 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_institution'),
        ('lost_and_found', '0017_auto_20210930_0424'),
    ]

    operations = [
        migrations.AddField(
            model_name='founditem',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lostitem',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='founditem',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='found_items', related_query_name='found_item', to='core.institution'),
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lost_items', related_query_name='lost_item', to='core.institution'),
        ),
    ]
