# Generated by Django 3.1.3 on 2021-10-07 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_institution'),
        ('users', '0014_auto_20211007_0128'),
        ('lost_and_found', '0018_auto_20211002_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='founditem',
            name='area_found',
            field=models.CharField(help_text='Where did you find the item?', max_length=250, verbose_name='Area found'),
        ),
        migrations.AlterField(
            model_name='founditem',
            name='area_found_en',
            field=models.CharField(help_text='Where did you find the item?', max_length=250, null=True, verbose_name='Area found'),
        ),
        migrations.AlterField(
            model_name='founditem',
            name='area_found_fr',
            field=models.CharField(help_text='Where did you find the item?', max_length=250, null=True, verbose_name='Area found'),
        ),
        migrations.AlterField(
            model_name='founditem',
            name='contact_numbers',
            field=models.ManyToManyField(related_name='_founditem_contact_numbers_+', to='users.PhoneNumber', verbose_name='Contact numbers'),
        ),
        migrations.AlterField(
            model_name='founditem',
            name='how_found',
            field=models.TextField(help_text='Explain how you found the item', verbose_name='How found'),
        ),
        migrations.AlterField(
            model_name='founditem',
            name='how_found_en',
            field=models.TextField(help_text='Explain how you found the item', null=True, verbose_name='How found'),
        ),
        migrations.AlterField(
            model_name='founditem',
            name='how_found_fr',
            field=models.TextField(help_text='Explain how you found the item', null=True, verbose_name='How found'),
        ),
        migrations.AlterField(
            model_name='founditem',
            name='item_found',
            field=models.CharField(help_text='What have you found?', max_length=100, verbose_name='Item found'),
        ),
        migrations.AlterField(
            model_name='founditem',
            name='item_found_en',
            field=models.CharField(help_text='What have you found?', max_length=100, null=True, verbose_name='Item found'),
        ),
        migrations.AlterField(
            model_name='founditem',
            name='item_found_fr',
            field=models.CharField(help_text='What have you found?', max_length=100, null=True, verbose_name='Item found'),
        ),
        migrations.AlterField(
            model_name='founditem',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='found_items', related_query_name='found_item', to='core.institution', verbose_name='School'),
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='area_lost',
            field=models.CharField(help_text='Where do you think you lost the item?', max_length=250, verbose_name='Area lost'),
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='area_lost_en',
            field=models.CharField(help_text='Where do you think you lost the item?', max_length=250, null=True, verbose_name='Area lost'),
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='area_lost_fr',
            field=models.CharField(help_text='Where do you think you lost the item?', max_length=250, null=True, verbose_name='Area lost'),
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='bounty',
            field=models.CharField(blank=True, help_text='Award/bounty given to the person who will return the item. Make sure that you are in possession of the award. <br> This is optional but can be used as motivation.', max_length=100, null=True, verbose_name='Bounty'),
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='bounty_en',
            field=models.CharField(blank=True, help_text='Award/bounty given to the person who will return the item. Make sure that you are in possession of the award. <br> This is optional but can be used as motivation.', max_length=100, null=True, verbose_name='Bounty'),
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='bounty_fr',
            field=models.CharField(blank=True, help_text='Award/bounty given to the person who will return the item. Make sure that you are in possession of the award. <br> This is optional but can be used as motivation.', max_length=100, null=True, verbose_name='Bounty'),
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='contact_numbers',
            field=models.ManyToManyField(related_name='_lostitem_contact_numbers_+', to='users.PhoneNumber', verbose_name='Contact numbers'),
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='how_lost',
            field=models.TextField(default='Good day, ... ', help_text='Explain how you think you lost the item, stating areas you passed across or visited', verbose_name='How lost'),
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='how_lost_en',
            field=models.TextField(default='Good day, ... ', help_text='Explain how you think you lost the item, stating areas you passed across or visited', null=True, verbose_name='How lost'),
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='how_lost_fr',
            field=models.TextField(default='Good day, ... ', help_text='Explain how you think you lost the item, stating areas you passed across or visited', null=True, verbose_name='How lost'),
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='item_description',
            field=models.TextField(help_text='Describe the lost item stating its important aspects.', verbose_name='Item description'),
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='item_description_en',
            field=models.TextField(help_text='Describe the lost item stating its important aspects.', null=True, verbose_name='Item description'),
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='item_description_fr',
            field=models.TextField(help_text='Describe the lost item stating its important aspects.', null=True, verbose_name='Item description'),
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='item_lost',
            field=models.CharField(help_text='What have you lost?', max_length=100, verbose_name='Item lost'),
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='item_lost_en',
            field=models.CharField(help_text='What have you lost?', max_length=100, null=True, verbose_name='Item lost'),
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='item_lost_fr',
            field=models.CharField(help_text='What have you lost?', max_length=100, null=True, verbose_name='Item lost'),
        ),
    ]
