# Generated by Django 3.1.3 on 2021-10-09 04:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lost_and_found', '0020_auto_20211008_0455'),
    ]

    operations = [
        migrations.AddField(
            model_name='founditem',
            name='bookmarkers',
            field=models.ManyToManyField(blank=True, related_name='bookmarked_found_items', related_query_name='bookmarked_found_item', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lostitem',
            name='bookmarkers',
            field=models.ManyToManyField(blank=True, related_name='bookmarked_lost_items', related_query_name='bookmarked_lost_item', to=settings.AUTH_USER_MODEL),
        ),
    ]
