# Generated by Django 3.1.3 on 2021-10-15 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost_and_found', '0022_auto_20211013_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='founditem',
            name='update_language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('fr', 'French')], editable=False, help_text='Language in which last update was done', max_length=2),
        ),
        migrations.AddField(
            model_name='lostitem',
            name='update_language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('fr', 'French')], editable=False, help_text='Language in which last update was done', max_length=2),
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='how_lost',
            field=models.TextField(default='Good day, ', help_text='Explain how you think you lost the item, stating areas you passed across or visited', verbose_name='How lost'),
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='how_lost_en',
            field=models.TextField(default='Good day, ', help_text='Explain how you think you lost the item, stating areas you passed across or visited', null=True, verbose_name='How lost'),
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='how_lost_fr',
            field=models.TextField(default='Good day, ', help_text='Explain how you think you lost the item, stating areas you passed across or visited', null=True, verbose_name='How lost'),
        ),
    ]
