# Generated by Django 3.1.3 on 2021-08-20 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaFollow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitter_follow', models.CharField(blank=True, max_length=30, null=True, verbose_name='Twitter link or username')),
                ('facebook_follow', models.CharField(blank=True, max_length=30, null=True, verbose_name='Facebook link or username')),
                ('instagram_follow', models.CharField(blank=True, max_length=30, null=True, verbose_name='Instagram link or username')),
            ],
        ),
    ]
