# Generated by Django 3.1.3 on 2021-08-18 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0018_auto_20210810_1424'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='social_profile', serialize=False, to='users.user')),
                ('current_relationship', models.CharField(choices=[('single', 'Single'), ('dating', 'Dating'), ('engaged', 'Engaged'), ('married', 'Married'), ('undecided', 'Undecided')], max_length=15)),
                ('interested_relationship', models.CharField(choices=[('chatting', 'Being chat pals'), ('studies', 'Being study pals'), ('clubbing', 'Clubbing this weekend'), ('dating', 'Dating'), ('flirting', 'Flirting'), ('friendship', 'Friendship'), ('hanging_out', 'Hanging out this weekend'), ('marriage', 'Marriage'), ('undecided', 'Undecided')], max_length=15)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=2)),
                ('about_me', models.TextField(verbose_name='A little about me')),
                ('interests', models.TextField(verbose_name='My interests')),
                ('hobbies', models.TextField(verbose_name='My hobbies')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('is_visible', models.BooleanField(default=False, help_text='Enable Socialize and allow other users to be able to view my profile.')),
                ('birth_date', models.DateField(blank=True, help_text='Please at least enter the correct birth year.', null=True, verbose_name='Birthday')),
            ],
        ),
    ]
