# Generated by Django 3.1.3 on 2021-08-18 01:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('socialize', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialprofile',
            name='birth_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Please at least enter the correct birth year.', verbose_name='Birthday'),
            preserve_default=False,
        ),
    ]
