# Generated by Django 3.1.3 on 2021-09-01 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialize', '0002_socialprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialprofile',
            name='level',
            field=models.CharField(choices=[('O', 'Ordinary Level'), ('A', 'Advanced Level'), ('BEPC', 'BEPC'), ('PROB', 'Probatoire'), ('BAC', 'Baccalaureat'), ('BACH', "HND/Bachelor's"), ('BTS', 'BTS'), ('LIC', 'Licence'), ('MS', "Master's"), ('PhD', 'Doctorate')], default=None, max_length=5, verbose_name='Level'),
        ),
    ]
