# Generated by Django 3.1.3 on 2021-09-04 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialize', '0003_auto_20210901_0208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialprofile',
            name='is_visible',
        ),
        migrations.AddField(
            model_name='socialmediafollow',
            name='github_follow',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Github link or username'),
        ),
        migrations.AddField(
            model_name='socialmediafollow',
            name='tiktok_follow',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tiktok link or username'),
        ),
        migrations.AddField(
            model_name='socialmediafollow',
            name='website_follow',
            field=models.CharField(blank=True, help_text='An example could be a link to a YouTube channel or Likee profile, etc.. <br> Separate links with a comma or semicolon', max_length=250, null=True, verbose_name='Other website links'),
        ),
        migrations.AlterField(
            model_name='socialmediafollow',
            name='facebook_follow',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Facebook link or username'),
        ),
        migrations.AlterField(
            model_name='socialmediafollow',
            name='instagram_follow',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Instagram link or username'),
        ),
        migrations.AlterField(
            model_name='socialmediafollow',
            name='twitter_follow',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Twitter link or username'),
        ),
    ]
