# Generated by Django 3.1.3 on 2021-09-05 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialize', '0005_auto_20210904_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialprofile',
            name='level',
            field=models.CharField(choices=[('N/A', '--------'), ('O', 'Ordinary Level'), ('A', 'Advanced Level'), ('BEPC', 'BEPC'), ('PROB', 'Probatoire'), ('BAC', 'Baccalaureat'), ('BACH', "HND/Bachelor's"), ('BTS', 'BTS'), ('LIC', 'Licence'), ('MS', "Master's"), ('PhD', 'Doctorate')], default='N/A', max_length=5, verbose_name='Level'),
        ),
    ]
