# Generated by Django 3.1.3 on 2021-08-19 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialize', '0005_auto_20210818_0304'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialprofile',
            name='department',
            field=models.CharField(default='d', max_length=30, verbose_name='Department'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='socialprofile',
            name='department_en',
            field=models.CharField(max_length=30, null=True, verbose_name='Department'),
        ),
        migrations.AddField(
            model_name='socialprofile',
            name='department_fr',
            field=models.CharField(max_length=30, null=True, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='socialprofile',
            name='current_relationship',
            field=models.CharField(choices=[('single', 'Single'), ('dating', 'Dating'), ('engaged', 'Engaged'), ('married', 'Married'), ('undecided', 'Undecided')], default=None, max_length=15, verbose_name='Current relationship'),
        ),
        migrations.AlterField(
            model_name='socialprofile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=2, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='socialprofile',
            name='interested_relationship',
            field=models.CharField(choices=[('chatting', 'Being chat pals'), ('studies', 'Being study pals'), ('clubbing', 'Clubbing this weekend'), ('dating', 'Dating'), ('flirting', 'Flirting'), ('friendship', 'Friendship'), ('hanging_out', 'Hanging out this weekend'), ('marriage', 'Marriage'), ('undecided', 'Undecided')], default=None, max_length=15, verbose_name='Interested relationship'),
        ),
        migrations.AlterField(
            model_name='socialprofile',
            name='is_visible',
            field=models.BooleanField(default=False, help_text='<br>Enable Socialize and allow other users to be able to view my profile.', verbose_name='Profile visible to other users'),
        ),
        migrations.AlterField(
            model_name='socialprofile',
            name='level',
            field=models.CharField(choices=[('L1', 'Level 1'), ('L2', 'Level 2'), ('L3', 'Level 3'), ('L4', 'Level 5'), ('M', 'Masters'), ('PhD', 'Doctorate'), ('Other', 'Other')], default=None, max_length=7, verbose_name='Level'),
        ),
    ]
