# Generated by Django 3.1.3 on 2021-11-24 22:55

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('socialize', '0005_auto_20211114_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialprofile',
            name='profile_image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, height_field='height', upload_to='profile_pictures/', verbose_name='Profile image', width_field='width'),
        ),
    ]
