# Generated by Django 3.1.3 on 2021-08-19 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialize', '0006_auto_20210819_0104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialprofile',
            name='interests',
        ),
        migrations.RemoveField(
            model_name='socialprofile',
            name='interests_en',
        ),
        migrations.RemoveField(
            model_name='socialprofile',
            name='interests_fr',
        ),
        migrations.AlterField(
            model_name='socialprofile',
            name='hobbies',
            field=models.TextField(verbose_name='My hobbies and interests'),
        ),
        migrations.AlterField(
            model_name='socialprofile',
            name='hobbies_en',
            field=models.TextField(null=True, verbose_name='My hobbies and interests'),
        ),
        migrations.AlterField(
            model_name='socialprofile',
            name='hobbies_fr',
            field=models.TextField(null=True, verbose_name='My hobbies and interests'),
        ),
    ]
