# Generated by Django 3.1.3 on 2021-11-24 23:45

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('socialize', '0006_auto_20211124_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialprofile',
            name='profile_image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to='profile_pictures/', verbose_name='Profile image'),
        ),
    ]
