# Generated by Django 3.1.3 on 2021-09-10 03:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('socialize', '0007_auto_20210908_2129'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialprofile',
            options={'ordering': ['-creation_datetime']},
        ),
        migrations.AddField(
            model_name='socialprofile',
            name='creation_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='socialprofile',
            index=models.Index(fields=['-creation_datetime'], name='socialize_s_creatio_e404ec_idx'),
        ),
    ]
