# Generated by Django 3.1.3 on 2021-09-25 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialize', '0008_auto_20210910_0345'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialprofile',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='socialprofile',
            name='original_language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French')], default='en', max_length=2),
        ),
    ]
