# Generated by Django 3.1.3 on 2021-09-25 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialize', '0009_auto_20210925_0531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialprofile',
            name='original_language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French')], max_length=2),
        ),
    ]
