# Generated by Django 3.1.3 on 2021-09-25 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialize', '0010_auto_20210925_0534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialprofile',
            name='original_language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French')], editable=False, max_length=2),
        ),
    ]
