# Generated by Django 3.1.3 on 2021-10-02 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0024_auto_20210930_0424'),
        ('socialize', '0011_auto_20210925_0538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialprofile',
            name='about_me',
            field=models.TextField(blank=True, verbose_name='A little about me'),
        ),
        migrations.AlterField(
            model_name='socialprofile',
            name='about_me_en',
            field=models.TextField(blank=True, null=True, verbose_name='A little about me'),
        ),
        migrations.AlterField(
            model_name='socialprofile',
            name='about_me_fr',
            field=models.TextField(blank=True, null=True, verbose_name='A little about me'),
        ),
        migrations.AlterField(
            model_name='socialprofile',
            name='birth_date',
            field=models.DateField(help_text="Please at least enter the correct birth year. <br>Your birth date and age won't be visible to other users.", verbose_name='Birthday'),
        ),
        migrations.AlterField(
            model_name='socialprofile',
            name='current_relationship',
            field=models.CharField(choices=[('single', 'Single'), ('dating', 'Dating'), ('engaged', 'Engaged'), ('married', 'Married'), ('undecided', 'Undecided')], default='single', max_length=15, verbose_name='Current relationship'),
        ),
        migrations.AlterField(
            model_name='socialprofile',
            name='department',
            field=models.CharField(help_text='Enter your study speciality', max_length=30, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='socialprofile',
            name='department_en',
            field=models.CharField(help_text='Enter your study speciality', max_length=30, null=True, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='socialprofile',
            name='department_fr',
            field=models.CharField(help_text='Enter your study speciality', max_length=30, null=True, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='socialprofile',
            name='hobbies',
            field=models.TextField(blank=True, verbose_name='My hobbies and interests'),
        ),
        migrations.AlterField(
            model_name='socialprofile',
            name='hobbies_en',
            field=models.TextField(blank=True, null=True, verbose_name='My hobbies and interests'),
        ),
        migrations.AlterField(
            model_name='socialprofile',
            name='hobbies_fr',
            field=models.TextField(blank=True, null=True, verbose_name='My hobbies and interests'),
        ),
        migrations.AlterField(
            model_name='socialprofile',
            name='interested_relationship',
            field=models.CharField(choices=[('none', 'Not interested'), ('chatting', 'Being chat pals'), ('studies', 'Being study pals'), ('clubbing', 'Clubbing this weekend'), ('dating', 'Dating'), ('flirting', 'Flirting'), ('friendship', 'Friendship'), ('hanging_out', 'Hanging out this weekend'), ('marriage', 'Marriage'), ('undecided', 'Undecided')], default='none', max_length=15, verbose_name='Interested relationship'),
        ),
        migrations.AlterField(
            model_name='socialprofile',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_profiles', related_query_name='social_profile', to='marketplace.institution'),
        ),
    ]
