# Generated by Django 3.1.3 on 2021-10-03 17:53

import core.model_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialize', '0013_auto_20211002_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediafollow',
            name='email',
            field=core.model_fields.NormalizedEmailField(blank=True, max_length=50, null=True, verbose_name='Email address'),
        ),
        migrations.AlterField(
            model_name='socialprofile',
            name='level',
            field=models.CharField(choices=[('O', 'Ordinary Level'), ('A', 'Advanced Level'), ('BEPC', 'BEPC'), ('PROB', 'Probatoire'), ('BAC', 'Baccalaureat'), ('BACH', "HND/Bachelor's"), ('BTS', 'BTS'), ('LIC', 'Licence'), ('MS', "Master's"), ('PhD', 'Doctorate')], max_length=5, verbose_name='Level'),
        ),
    ]
