# Generated by Django 3.1.3 on 2021-10-03 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialize', '0014_auto_20211003_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialprofile',
            name='level',
            field=models.CharField(choices=[('O', 'Ordinary Level'), ('A', 'Advanced Level'), ('BEPC', 'BEPC'), ('PROB', 'Probatoire'), ('BAC', 'Baccalaureat'), ('BACH', "HND/Bachelor's"), ('BTS', 'BTS'), ('LIC', 'Licence'), ('MS', "Master's"), ('PhD', 'Doctorate')], default='O', max_length=5, verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='socialprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/', verbose_name='Profile image'),
        ),
    ]
