# Generated by Django 3.1.3 on 2021-10-07 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_institution'),
        ('socialize', '0015_auto_20211003_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialprofile',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_profiles', related_query_name='social_profile', to='core.institution', verbose_name='School'),
        ),
    ]
