# Generated by Django 3.1.3 on 2021-10-09 04:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('socialize', '0016_auto_20211007_0128'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialprofile',
            name='bookmarkers',
            field=models.ManyToManyField(blank=True, related_name='bookmarked_social_profiles', related_query_name='bookmarked_social_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
