# Generated by Django 3.1.3 on 2021-10-12 01:43

import core.model_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialize', '0017_socialprofile_bookmarkers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmediafollow',
            name='email',
            field=core.model_fields.NormalizedEmailField(blank=True, default='', max_length=50, verbose_name='Email address'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='socialmediafollow',
            name='facebook_follow',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Facebook link or username'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='socialmediafollow',
            name='github_follow',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='GitHub link or username'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='socialmediafollow',
            name='instagram_follow',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Instagram link or username'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='socialmediafollow',
            name='tiktok_follow',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Tiktok link or username'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='socialmediafollow',
            name='twitter_follow',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Twitter link or username'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='socialmediafollow',
            name='website_follow',
            field=models.CharField(blank=True, default='', help_text='An example could be a link to a YouTube channel or Likee profile, etc.. <br> Separate multiple links with a semicolon.', max_length=250, verbose_name='Other website links'),
            preserve_default=False,
        ),
    ]
