# Generated by Django 3.1.3 on 2021-10-14 01:36

import core.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialize', '0018_auto_20211012_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialprofile',
            name='profile_image',
            field=models.ImageField(blank=True, default='', storage=core.storage_backends.PublicMediaStorage(), upload_to='profile_pictures/', verbose_name='Profile image'),
            preserve_default=False,
        ),
    ]
