# Generated by Django 3.1.3 on 2021-10-15 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialize', '0019_auto_20211014_0136'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialprofile',
            name='update_language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('fr', 'French')], editable=False, max_length=2),
        ),
    ]
