# Generated by Django 3.1.3 on 2021-10-15 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialize', '0020_socialprofile_update_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialprofile',
            name='department',
        ),
        migrations.RemoveField(
            model_name='socialprofile',
            name='department_en',
        ),
        migrations.RemoveField(
            model_name='socialprofile',
            name='department_fr',
        ),
        migrations.AddField(
            model_name='socialprofile',
            name='speciality',
            field=models.CharField(default='', help_text='Enter your study department or speciality', max_length=30, verbose_name='Speciality'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='socialprofile',
            name='speciality_en',
            field=models.CharField(help_text='Enter your study department or speciality', max_length=30, null=True, verbose_name='Speciality'),
        ),
        migrations.AddField(
            model_name='socialprofile',
            name='speciality_fr',
            field=models.CharField(help_text='Enter your study department or speciality', max_length=30, null=True, verbose_name='Speciality'),
        ),
    ]
