# Generated by Django 3.1.3 on 2021-10-17 22:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('past_papers', '0001_initial'),
        ('core', '0001_initial'),
        ('qa_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastpaper',
            name='bookmarkers',
            field=models.ManyToManyField(blank=True, related_name='bookmarked_past_papers', related_query_name='bookmarked_past_paper', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pastpaper',
            name='poster',
            field=models.ForeignKey(on_delete=models.SET(users.models.get_dummy_user), related_name='past_papers', related_query_name='past_paper', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pastpaper',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='past_papers', related_query_name='past_paper', to='core.institution', verbose_name='School'),
        ),
        migrations.AddField(
            model_name='pastpaper',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='past_papers', related_query_name='past_paper', to='qa_site.subject', verbose_name='Subject'),
        ),
        migrations.AddField(
            model_name='comment',
            name='past_paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', related_query_name='comment', to='past_papers.pastpaper'),
        ),
        migrations.AddField(
            model_name='comment',
            name='poster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='past_paper_comments', related_query_name='past_paper_comment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='pastpaper',
            index=models.Index(fields=['-posted_datetime'], name='past_papers_posted__3269e7_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['-posted_datetime'], name='past_papers_posted__90d67f_idx'),
        ),
    ]
