# Generated by Django 3.1.3 on 2021-11-01 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('past_papers', '0002_auto_20211017_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastpaper',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='Title'),
        ),
    ]
