# Generated by Django 3.1.3 on 2021-11-13 07:06

import core.model_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('past_papers', '0004_auto_20211102_0249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastpaper',
            name='file',
            field=core.model_fields.DynamicStorageFileField(blank=True, upload_to='past_papers/'),
        ),
        migrations.AlterField(
            model_name='pastpaperphoto',
            name='file',
            field=core.model_fields.DynamicStorageFileField(upload_to='past_paper_photos/'),
        ),
    ]
