# Generated by Django 3.2 on 2022-09-28 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('past_papers', '0016_alter_comment_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(max_length=3000, verbose_name='Content'),
        ),
    ]
