# Generated by Django 3.2 on 2022-09-28 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('past_papers', '0017_alter_comment_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='PastPaperBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookmark_datetime', models.DateTimeField(auto_now_add=True)),
                ('bookmarker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('past_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='past_papers.pastpaper')),
            ],
        ),
        migrations.AddField(
            model_name='pastpaper',
            name='bookmarkers',
            field=models.ManyToManyField(blank=True, related_name='bookmarked_past_papers', related_query_name='bookmarked_past_paper', through='past_papers.PastPaperBookmark', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='pastpaperbookmark',
            constraint=models.UniqueConstraint(fields=('past_paper', 'bookmarker'), name='unique_past_paper_bookmark'),
        ),
    ]
