# Generated by Django 3.2 on 2022-09-28 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('past_papers', '0018_auto_20220928_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastpaper',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
    ]
