# Generated by Django 3.2 on 2022-12-04 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('past_papers', '0019_alter_pastpaper_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastpaper',
            name='level',
            field=models.CharField(choices=[('O', 'Ordinary Level'), ('A', 'Advanced Level'), ('BEPC', 'BEPC'), ('PROB', 'Probatoire'), ('BAC', 'Baccalaureat'), ('BACH', "HND/Bachelor's"), ('BTS', 'BTS'), ('LIC', 'Licence'), ('MS', "Master's"), ('PhD', 'Doctorate'), ('OTH', 'Other')], max_length=5, verbose_name='Level'),
        ),
    ]
