# Generated by Django 3.1.3 on 2021-10-17 22:43

import ckeditor.fields
import core.fields
import core.storage_backends
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35, verbose_name='Name')),
                ('name_en', models.CharField(max_length=35, null=True, verbose_name='Name')),
                ('name_fr', models.CharField(max_length=35, null=True, verbose_name='Name')),
                ('datetime_added', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Ad Categories',
            },
        ),
        migrations.CreateModel(
            name='AdListing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('slug', models.SlugField(max_length=255)),
                ('slug_en', models.SlugField(max_length=255, null=True)),
                ('slug_fr', models.SlugField(max_length=255, null=True)),
                ('posted_datetime', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('original_language', models.CharField(choices=[('en', 'English'), ('fr', 'French')], editable=False, help_text='Language in which post was created', max_length=2)),
                ('update_language', models.CharField(blank=True, choices=[('en', 'English'), ('fr', 'French')], editable=False, help_text='Language in which last update was done', max_length=2)),
                ('contact_email', core.fields.NormalizedEmailField(help_text='Email address to contact; enter a valid email.', max_length=50, validators=[django.core.validators.EmailValidator()], verbose_name='Email address')),
                ('title', models.CharField(help_text='A descriptive title helps buyers find your item. <br> State exactly what your post is.', max_length=100, verbose_name='Title')),
                ('title_en', models.CharField(help_text='A descriptive title helps buyers find your item. <br> State exactly what your post is.', max_length=100, null=True, verbose_name='Title')),
                ('title_fr', models.CharField(help_text='A descriptive title helps buyers find your item. <br> State exactly what your post is.', max_length=100, null=True, verbose_name='Title')),
                ('description', ckeditor.fields.RichTextField(help_text='Describe the your post and provide complete and accurate details. Use a clear and concise format.', verbose_name='Description')),
                ('description_en', ckeditor.fields.RichTextField(help_text='Describe the your post and provide complete and accurate details. Use a clear and concise format.', null=True, verbose_name='Description')),
                ('description_fr', ckeditor.fields.RichTextField(help_text='Describe the your post and provide complete and accurate details. Use a clear and concise format.', null=True, verbose_name='Description')),
                ('pricing', models.CharField(default='-', help_text='Allow this field empty for free products and services or if the pricing is in the advert description.', max_length=40, verbose_name='Pricing')),
                ('pricing_en', models.CharField(default='-', help_text='Allow this field empty for free products and services or if the pricing is in the advert description.', max_length=40, null=True, verbose_name='Pricing')),
                ('pricing_fr', models.CharField(default='-', help_text='Allow this field empty for free products and services or if the pricing is in the advert description.', max_length=40, null=True, verbose_name='Pricing')),
            ],
            options={
                'ordering': ['-posted_datetime'],
            },
        ),
        migrations.CreateModel(
            name='AdListingPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(storage=core.storage_backends.PublicMediaStorage(), upload_to='ad_photos/')),
                ('upload_datetime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Ad Listing Photos',
            },
        ),
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('name_en', models.CharField(max_length=30, null=True, verbose_name='Name')),
                ('name_fr', models.CharField(max_length=30, null=True, verbose_name='Name')),
                ('datetime_added', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Item Categories',
            },
        ),
        migrations.CreateModel(
            name='ItemListing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('slug', models.SlugField(max_length=255)),
                ('slug_en', models.SlugField(max_length=255, null=True)),
                ('slug_fr', models.SlugField(max_length=255, null=True)),
                ('posted_datetime', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('original_language', models.CharField(choices=[('en', 'English'), ('fr', 'French')], editable=False, help_text='Language in which post was created', max_length=2)),
                ('update_language', models.CharField(blank=True, choices=[('en', 'English'), ('fr', 'French')], editable=False, help_text='Language in which last update was done', max_length=2)),
                ('contact_email', core.fields.NormalizedEmailField(help_text='Email address to contact; enter a valid email.', max_length=50, validators=[django.core.validators.EmailValidator()], verbose_name='Email address')),
                ('title', models.CharField(help_text='A descriptive title helps buyers find your item. <br> State exactly what your post is.', max_length=100, verbose_name='Title')),
                ('title_en', models.CharField(help_text='A descriptive title helps buyers find your item. <br> State exactly what your post is.', max_length=100, null=True, verbose_name='Title')),
                ('title_fr', models.CharField(help_text='A descriptive title helps buyers find your item. <br> State exactly what your post is.', max_length=100, null=True, verbose_name='Title')),
                ('description', ckeditor.fields.RichTextField(help_text='Describe the your post and provide complete and accurate details. Use a clear and concise format.', verbose_name='Description')),
                ('description_en', ckeditor.fields.RichTextField(help_text='Describe the your post and provide complete and accurate details. Use a clear and concise format.', null=True, verbose_name='Description')),
                ('description_fr', ckeditor.fields.RichTextField(help_text='Describe the your post and provide complete and accurate details. Use a clear and concise format.', null=True, verbose_name='Description')),
                ('condition', models.CharField(choices=[('N', 'New'), ('U', 'Used'), ('D', 'Defective(some parts are not working)')], default='N', help_text="Select the condition of the item you're listing.", max_length=3, verbose_name='Condition')),
                ('condition_description', models.TextField(blank=True, help_text='Provide details about the condition of a non brand-new item, including any defects or flaws, so that buyers know exactly what to expect.', null=True, verbose_name='Condition description')),
                ('condition_description_en', models.TextField(blank=True, help_text='Provide details about the condition of a non brand-new item, including any defects or flaws, so that buyers know exactly what to expect.', null=True, verbose_name='Condition description')),
                ('condition_description_fr', models.TextField(blank=True, help_text='Provide details about the condition of a non brand-new item, including any defects or flaws, so that buyers know exactly what to expect.', null=True, verbose_name='Condition description')),
                ('price', models.PositiveIntegerField(help_text='Figures and spaces only, no commas or dots. <br> Enter <b>0</b> for free products or services.', verbose_name='Price')),
            ],
            options={
                'verbose_name_plural': 'Item Listings',
                'ordering': ['-posted_datetime'],
            },
        ),
        migrations.CreateModel(
            name='ItemSubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35, verbose_name='Name')),
                ('name_en', models.CharField(max_length=35, null=True, verbose_name='Name')),
                ('name_fr', models.CharField(max_length=35, null=True, verbose_name='Name')),
                ('datetime_added', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('parent_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sub_categories', related_query_name='sub_category', to='marketplace.itemcategory')),
            ],
            options={
                'verbose_name_plural': 'Item SubCategories',
            },
        ),
        migrations.CreateModel(
            name='ItemListingPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(storage=core.storage_backends.PublicMediaStorage(), upload_to='item_photos/')),
                ('upload_datetime', models.DateTimeField(auto_now_add=True)),
                ('item_listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', related_query_name='photo', to='marketplace.itemlisting')),
            ],
            options={
                'verbose_name': 'Item Listing Photo',
                'verbose_name_plural': 'Item Listing Photos',
            },
        ),
    ]
