# Generated by Django 3.1.3 on 2021-10-17 22:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketplace', '0001_initial'),
        ('users', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemlisting',
            name='bookmarkers',
            field=models.ManyToManyField(blank=True, related_name='bookmarked_item_listings', related_query_name='bookmarked_item_listing', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itemlisting',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item_listings', related_query_name='item_listing', to='marketplace.itemcategory', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='itemlisting',
            name='contact_numbers',
            field=models.ManyToManyField(related_name='_itemlisting_contact_numbers_+', to='users.PhoneNumber', verbose_name='Contact numbers'),
        ),
        migrations.AddField(
            model_name='itemlisting',
            name='poster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_listings', related_query_name='item_listing', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itemlisting',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_listings', related_query_name='item_listing', to='core.institution', verbose_name='School'),
        ),
        migrations.AddField(
            model_name='itemlisting',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='item_listings', related_query_name='item_listing', to='marketplace.itemsubcategory', verbose_name='Sub category'),
        ),
        migrations.AddField(
            model_name='adlistingphoto',
            name='ad_listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', related_query_name='photo', to='marketplace.adlisting'),
        ),
        migrations.AddField(
            model_name='adlisting',
            name='bookmarkers',
            field=models.ManyToManyField(blank=True, related_name='bookmarked_ad_listings', related_query_name='bookmarked_ad_listing', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adlisting',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ad_listings', related_query_name='ad_listing', to='marketplace.adcategory', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='adlisting',
            name='contact_numbers',
            field=models.ManyToManyField(related_name='_adlisting_contact_numbers_+', to='users.PhoneNumber', verbose_name='Contact numbers'),
        ),
        migrations.AddField(
            model_name='adlisting',
            name='poster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_listings', related_query_name='ad_listing', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adlisting',
            name='school',
            field=models.ForeignKey(blank=True, help_text='Allow this field empty if this advert does not concern a particular school.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ad_listings', related_query_name='ad_listing', to='core.institution', verbose_name='School'),
        ),
        migrations.AddIndex(
            model_name='itemlisting',
            index=models.Index(fields=['-posted_datetime'], name='marketplace_posted__8b2114_idx'),
        ),
        migrations.AddIndex(
            model_name='adlisting',
            index=models.Index(fields=['-posted_datetime'], name='marketplace_posted__0a118c_idx'),
        ),
    ]
