# Generated by Django 3.1.3 on 2021-11-01 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_auto_20211017_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adlisting',
            name='title',
            field=models.CharField(help_text='A descriptive title helps buyers find your item. <br> State exactly what your post is.', max_length=100, unique=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='adlisting',
            name='title_en',
            field=models.CharField(help_text='A descriptive title helps buyers find your item. <br> State exactly what your post is.', max_length=100, null=True, unique=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='adlisting',
            name='title_fr',
            field=models.CharField(help_text='A descriptive title helps buyers find your item. <br> State exactly what your post is.', max_length=100, null=True, unique=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='itemlisting',
            name='title',
            field=models.CharField(help_text='A descriptive title helps buyers find your item. <br> State exactly what your post is.', max_length=100, unique=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='itemlisting',
            name='title_en',
            field=models.CharField(help_text='A descriptive title helps buyers find your item. <br> State exactly what your post is.', max_length=100, null=True, unique=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='itemlisting',
            name='title_fr',
            field=models.CharField(help_text='A descriptive title helps buyers find your item. <br> State exactly what your post is.', max_length=100, null=True, unique=True, verbose_name='Title'),
        ),
    ]
