# Generated by Django 3.2 on 2022-07-24 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0014_auto_20220718_2154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemlisting',
            name='category',
        ),
    ]
