# Generated by Django 3.2 on 2022-07-24 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_city_options'),
        ('marketplace', '0015_remove_itemlisting_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adlisting',
            name='school',
        ),
        migrations.RemoveField(
            model_name='itemlisting',
            name='school',
        ),
        migrations.AddField(
            model_name='adlisting',
            name='city',
            field=models.ForeignKey(blank=True, help_text='Allow this field empty if this advert does not concern a particular city.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ad_listings', related_query_name='ad_listing', to='core.city', verbose_name='City'),
        ),
        migrations.AddField(
            model_name='itemlisting',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='item_listings', related_query_name='item_listing', to='core.city', verbose_name='City'),
            preserve_default=False,
        ),
    ]
