# Generated by Django 3.2 on 2022-09-28 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0018_auto_20220928_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemlisting',
            name='condition_description',
            field=models.TextField(blank=True, help_text='Provide details about the condition of a non brand-new item, including any defects or flaws, so that buyers know exactly what to expect.', max_length=3000, verbose_name='Condition description'),
        ),
        migrations.AlterField(
            model_name='itemlisting',
            name='condition_description_en',
            field=models.TextField(blank=True, help_text='Provide details about the condition of a non brand-new item, including any defects or flaws, so that buyers know exactly what to expect.', max_length=3000, null=True, verbose_name='Condition description'),
        ),
        migrations.AlterField(
            model_name='itemlisting',
            name='condition_description_fr',
            field=models.TextField(blank=True, help_text='Provide details about the condition of a non brand-new item, including any defects or flaws, so that buyers know exactly what to expect.', max_length=3000, null=True, verbose_name='Condition description'),
        ),
    ]
