# Generated by Django 3.2 on 2022-09-28 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketplace', '0019_auto_20220928_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemListingBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookmark_datetime', models.DateTimeField(auto_now_add=True)),
                ('bookmarker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('item_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='marketplace.itemlisting')),
            ],
        ),
        migrations.CreateModel(
            name='AdListingBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookmark_datetime', models.DateTimeField(auto_now_add=True)),
                ('ad_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='marketplace.adlisting')),
                ('bookmarker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='adlisting',
            name='bookmarkers',
            field=models.ManyToManyField(blank=True, related_name='bookmarked_ad_listings', related_query_name='bookmarked_ad_listing', through='marketplace.AdListingBookmark', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itemlisting',
            name='bookmarkers',
            field=models.ManyToManyField(blank=True, related_name='bookmarked_item_listings', related_query_name='bookmarked_item_listing', through='marketplace.ItemListingBookmark', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='itemlistingbookmark',
            constraint=models.UniqueConstraint(fields=('item_listing', 'bookmarker'), name='unique_item_listing_bookmark'),
        ),
        migrations.AddConstraint(
            model_name='adlistingbookmark',
            constraint=models.UniqueConstraint(fields=('ad_listing', 'bookmarker'), name='unique_ad_listing_bookmark'),
        ),
    ]
