# Generated by Django 3.2 on 2022-09-28 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0020_auto_20220928_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adlisting',
            name='title',
            field=models.CharField(help_text='A descriptive title helps buyers find your item. <br> State exactly what your post is.', max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='adlisting',
            name='title_en',
            field=models.CharField(help_text='A descriptive title helps buyers find your item. <br> State exactly what your post is.', max_length=100, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='adlisting',
            name='title_fr',
            field=models.CharField(help_text='A descriptive title helps buyers find your item. <br> State exactly what your post is.', max_length=100, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='itemlisting',
            name='title',
            field=models.CharField(help_text='A descriptive title helps buyers find your item. <br> State exactly what your post is.', max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='itemlisting',
            name='title_en',
            field=models.CharField(help_text='A descriptive title helps buyers find your item. <br> State exactly what your post is.', max_length=100, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='itemlisting',
            name='title_fr',
            field=models.CharField(help_text='A descriptive title helps buyers find your item. <br> State exactly what your post is.', max_length=100, null=True, verbose_name='Title'),
        ),
    ]
