# Generated by Django 3.1.3 on 2021-09-26 22:03

import core.model_fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0006_auto_20210914_1623'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketplace', '0022_auto_20210926_2203'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100)),
                ('posted_datetime', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('original_language', models.CharField(choices=[('en', 'English'), ('fr', 'French')], editable=False, max_length=2)),
                ('contact_name', core.model_fields.FullNameField(help_text='Please use your real names.', max_length=25, verbose_name='Full name')),
                ('contact_email', core.model_fields.NormalizedEmailField(help_text='Email address to contact; enter a valid email.', max_length=50, validators=[django.core.validators.EmailValidator()], verbose_name='Email address')),
                ('item_requested', models.CharField(help_text='What item do you need?', max_length=100)),
                ('item_description', models.TextField(blank=True, help_text='Describe the item you are in need of, stating its important aspects. <br> You may allow this empty.', null=True)),
                ('price_at_hand', models.CharField(blank=True, help_text='How much are you willing to pay for the item? You may allow this empty.', max_length=20, null=True)),
                ('contact_numbers', models.ManyToManyField(related_name='_requesteditem_contact_numbers_+', to='users.PhoneNumber')),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_items', related_query_name='requested_item', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_items', related_query_name='requested_item', to='marketplace.institution')),
            ],
            options={
                'ordering': ['-posted_datetime'],
            },
        ),
        migrations.CreateModel(
            name='RequestedItemPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='requested_items_photos/')),
                ('upload_datetime', models.DateTimeField(auto_now_add=True)),
                ('requested_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', related_query_name='photo', to='requested_items.requesteditem')),
            ],
            options={
                'verbose_name': 'Requested Item Photo',
                'verbose_name_plural': 'Requested Items Photos',
            },
        ),
        migrations.AddIndex(
            model_name='requesteditem',
            index=models.Index(fields=['-posted_datetime'], name='requested_i_posted__6436cf_idx'),
        ),
    ]
