# Generated by Django 3.1.3 on 2021-09-30 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0024_auto_20210930_0424'),
        ('requested_items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesteditem',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='requested_items', related_query_name='requested_item', to='marketplace.itemcategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requesteditem',
            name='item_description_en',
            field=models.TextField(blank=True, help_text='Describe the item you are in need of, stating its important aspects. <br> You may allow this empty.', null=True),
        ),
        migrations.AddField(
            model_name='requesteditem',
            name='item_description_fr',
            field=models.TextField(blank=True, help_text='Describe the item you are in need of, stating its important aspects. <br> You may allow this empty.', null=True),
        ),
        migrations.AddField(
            model_name='requesteditem',
            name='item_requested_en',
            field=models.CharField(help_text='What item do you need?', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='requesteditem',
            name='item_requested_fr',
            field=models.CharField(help_text='What item do you need?', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='requesteditem',
            name='price_at_hand_en',
            field=models.CharField(blank=True, help_text='How much are you willing to pay for the item? You may allow this empty.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='requesteditem',
            name='price_at_hand_fr',
            field=models.CharField(blank=True, help_text='How much are you willing to pay for the item? You may allow this empty.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='requesteditem',
            name='slug_en',
            field=models.SlugField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='requesteditem',
            name='slug_fr',
            field=models.SlugField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='requesteditem',
            name='original_language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French')], editable=False, help_text='Language in which post was created', max_length=2),
        ),
        migrations.AlterField(
            model_name='requesteditem',
            name='school',
            field=models.ForeignKey(blank=True, help_text="Allow this empty if it doesn't concern a particular school", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requested_items', related_query_name='requested_item', to='marketplace.institution'),
        ),
        migrations.AlterField(
            model_name='requesteditem',
            name='slug',
            field=models.SlugField(max_length=255),
        ),
    ]
