# Generated by Django 3.1.3 on 2021-10-17 22:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketplace', '0002_auto_20211017_2243'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
        ('core', '0001_initial'),
        ('requested_items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesteditem',
            name='bookmarkers',
            field=models.ManyToManyField(blank=True, related_name='bookmarked_requested_items', related_query_name='bookmarked_requested_item', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='requesteditem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_items', related_query_name='requested_item', to='marketplace.itemcategory', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='requesteditem',
            name='contact_numbers',
            field=models.ManyToManyField(related_name='_requesteditem_contact_numbers_+', to='users.PhoneNumber', verbose_name='Contact numbers'),
        ),
        migrations.AddField(
            model_name='requesteditem',
            name='poster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_items', related_query_name='requested_item', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='requesteditem',
            name='school',
            field=models.ForeignKey(blank=True, help_text='Allow this field empty if you are willing to go to another area to buy the item, not in your school.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requested_items', related_query_name='requested_item', to='core.institution', verbose_name='School'),
        ),
        migrations.AddIndex(
            model_name='requesteditem',
            index=models.Index(fields=['-posted_datetime'], name='requested_i_posted__6436cf_idx'),
        ),
    ]
