# Generated by Django 3.1.3 on 2021-09-30 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requested_items', '0002_auto_20210930_0424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requesteditem',
            name='price_at_hand',
            field=models.CharField(default='-', help_text='How much are you willing to pay for the item? You may allow this empty.', max_length=20),
        ),
        migrations.AlterField(
            model_name='requesteditem',
            name='price_at_hand_en',
            field=models.CharField(default='-', help_text='How much are you willing to pay for the item? You may allow this empty.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='requesteditem',
            name='price_at_hand_fr',
            field=models.CharField(default='-', help_text='How much are you willing to pay for the item? You may allow this empty.', max_length=20, null=True),
        ),
    ]
