# Generated by Django 3.1.3 on 2021-09-30 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requested_items', '0003_auto_20210930_0448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requesteditem',
            name='item_description',
            field=models.TextField(default='', help_text='Describe the item you are in need of, stating its important aspects. <br> You may allow this empty.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='requesteditem',
            name='item_description_en',
            field=models.TextField(help_text='Describe the item you are in need of, stating its important aspects. <br> You may allow this empty.', null=True),
        ),
        migrations.AlterField(
            model_name='requesteditem',
            name='item_description_fr',
            field=models.TextField(help_text='Describe the item you are in need of, stating its important aspects. <br> You may allow this empty.', null=True),
        ),
    ]
