# Generated by Django 3.1.3 on 2021-10-02 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_institution'),
        ('requested_items', '0004_auto_20210930_0553'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesteditem',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='requesteditem',
            name='school',
            field=models.ForeignKey(blank=True, help_text="Allow this empty if it doesn't concern a particular school", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requested_items', related_query_name='requested_item', to='core.institution'),
        ),
    ]
