# Generated by Django 3.1.3 on 2021-10-07 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_institution'),
        ('marketplace', '0026_auto_20211007_0128'),
        ('users', '0014_auto_20211007_0128'),
        ('requested_items', '0005_auto_20211002_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requesteditem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_items', related_query_name='requested_item', to='marketplace.itemcategory', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='requesteditem',
            name='contact_numbers',
            field=models.ManyToManyField(related_name='_requesteditem_contact_numbers_+', to='users.PhoneNumber', verbose_name='Contact numbers'),
        ),
        migrations.AlterField(
            model_name='requesteditem',
            name='item_description',
            field=models.TextField(help_text='Describe the item you are in need of, stating its important aspects. <br>You may allow this field empty.', verbose_name='Item description'),
        ),
        migrations.AlterField(
            model_name='requesteditem',
            name='item_description_en',
            field=models.TextField(help_text='Describe the item you are in need of, stating its important aspects. <br>You may allow this field empty.', null=True, verbose_name='Item description'),
        ),
        migrations.AlterField(
            model_name='requesteditem',
            name='item_description_fr',
            field=models.TextField(help_text='Describe the item you are in need of, stating its important aspects. <br>You may allow this field empty.', null=True, verbose_name='Item description'),
        ),
        migrations.AlterField(
            model_name='requesteditem',
            name='item_requested',
            field=models.CharField(help_text='What item do you need?', max_length=100, verbose_name='Item requested'),
        ),
        migrations.AlterField(
            model_name='requesteditem',
            name='item_requested_en',
            field=models.CharField(help_text='What item do you need?', max_length=100, null=True, verbose_name='Item requested'),
        ),
        migrations.AlterField(
            model_name='requesteditem',
            name='item_requested_fr',
            field=models.CharField(help_text='What item do you need?', max_length=100, null=True, verbose_name='Item requested'),
        ),
        migrations.AlterField(
            model_name='requesteditem',
            name='price_at_hand',
            field=models.CharField(default='-', help_text='How much are you willing to pay for the item? You may allow this field empty.', max_length=20, verbose_name='Price at hand'),
        ),
        migrations.AlterField(
            model_name='requesteditem',
            name='price_at_hand_en',
            field=models.CharField(default='-', help_text='How much are you willing to pay for the item? You may allow this field empty.', max_length=20, null=True, verbose_name='Price at hand'),
        ),
        migrations.AlterField(
            model_name='requesteditem',
            name='price_at_hand_fr',
            field=models.CharField(default='-', help_text='How much are you willing to pay for the item? You may allow this field empty.', max_length=20, null=True, verbose_name='Price at hand'),
        ),
        migrations.AlterField(
            model_name='requesteditem',
            name='school',
            field=models.ForeignKey(blank=True, help_text="Allow this field empty if it doesn't concern a particular school", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requested_items', related_query_name='requested_item', to='core.institution', verbose_name='School'),
        ),
    ]
