# Generated by Django 3.1.3 on 2021-11-24 22:55

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('requested_items', '0006_auto_20211114_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requesteditemphoto',
            name='file',
            field=easy_thumbnails.fields.ThumbnailerImageField(height_field='height', upload_to='requested_items_photos/', width_field='width'),
        ),
    ]
