# Generated by Django 3.1.3 on 2021-10-13 18:25

import core.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requested_items', '0008_requesteditem_bookmarkers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requesteditemphoto',
            name='file',
            field=models.ImageField(storage=core.storage_backends.PublicMediaStorage(), upload_to='requested_items_photos/'),
        ),
    ]
