# Generated by Django 3.1.3 on 2021-10-15 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requested_items', '0009_auto_20211013_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesteditem',
            name='update_language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('fr', 'French')], editable=False, help_text='Language in which last update was done', max_length=2),
        ),
    ]
