# Generated by Django 3.1.3 on 2021-02-18 23:43

import ckeditor.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion
import hitcount.models
import core.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.DurationField(choices=[(datetime.timedelta(days=5), '5 days'), (datetime.timedelta(days=7), '1 week'), (datetime.timedelta(days=10), '10 days'), (datetime.timedelta(days=28), '1 month'), (datetime.timedelta(days=84), '3 months'), (datetime.timedelta(days=140), '5 months')], default=datetime.timedelta(days=5))),
                ('title', models.CharField(max_length=30)),
                ('slug', models.SlugField()),
                ('description', ckeditor.fields.RichTextField(blank=True)),
                ('datetime_added', models.DateTimeField(auto_now_add=True)),
                ('number_of_bookmarks', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, hitcount.models.HitCountMixin),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('location', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.DurationField(choices=[(datetime.timedelta(days=5), '5 days'), (datetime.timedelta(days=7), '1 week'), (datetime.timedelta(days=10), '10 days'), (datetime.timedelta(days=28), '1 month'), (datetime.timedelta(days=84), '3 months'), (datetime.timedelta(days=140), '5 months')], default=datetime.timedelta(days=5))),
                ('title', models.CharField(max_length=30)),
                ('slug', models.SlugField()),
                ('description', ckeditor.fields.RichTextField(blank=True)),
                ('datetime_added', models.DateTimeField(auto_now_add=True)),
                ('number_of_bookmarks', models.PositiveIntegerField(default=0)),
                ('condition', models.CharField(choices=[('BN', 'Brand new'), ('U', 'Used'), ('N', 'New'), ('D', 'For parts or not working')], default='N', help_text="Select the condition of the item you're listing", max_length=2)),
                ('condition_description', models.TextField(help_text='Provide details about the condition of a non brand new item, including any defects of flaws, so that buyers know exactly what to expect.')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, hitcount.models.HitCountMixin),
        ),
        migrations.CreateModel(
            name='MarketplaceProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reputation', models.PositiveIntegerField(default=1)),
                ('credit_points', models.PositiveIntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='ParentCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Parent Categories',
            },
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(choices=[('MTN', 'MTN'), ('Nexttel', 'Nexttel'), ('Orange', 'Orange'), ('CAMTEL', 'CAMTEL'), ('O', 'Other')], default='MTN', max_length=8)),
                ('number', models.CharField(help_text='Enter mobile number <b>(without +237)</b>', max_length=9, validators=[core.validators.validate_tel_number_length], verbose_name='Phone number')),
                ('can_whatsapp', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', related_query_name='phone_number', to='marketplace.marketplaceprofile')),
            ],
        ),
    ]
