# Generated by Django 3.1.3 on 2021-02-18 23:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplaceprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='marketplace.category'),
        ),
        migrations.AddField(
            model_name='item',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_posts', related_query_name='post', to='marketplace.institution'),
        ),
        migrations.AddField(
            model_name='item',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='marketplace.marketplaceprofile'),
        ),
        migrations.AddField(
            model_name='category',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='marketplace.parentcategory'),
        ),
        migrations.AddField(
            model_name='ad',
            name='category',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='marketplace.category'),
        ),
        migrations.AddField(
            model_name='ad',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_posts', related_query_name='post', to='marketplace.institution'),
        ),
        migrations.AddField(
            model_name='ad',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='marketplace.marketplaceprofile'),
        ),
    ]
