# Generated by Django 3.1.3 on 2021-08-20 21:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_auto_20210820_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adlisting',
            name='duration',
            field=models.DurationField(choices=[(datetime.timedelta(days=3), '3 days'), (datetime.timedelta(days=5), '5 days'), (datetime.timedelta(days=7), '1 week'), (datetime.timedelta(days=10), '10 days'), (datetime.timedelta(days=28), '1 month')], default=datetime.timedelta(days=28), help_text='For how long should your post be available'),
        ),
        migrations.AlterField(
            model_name='adlisting',
            name='institution',
            field=models.ForeignKey(blank=True, help_text='Allow this empty if this advert concerns no particular institution.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ad_listings', related_query_name='ad_listing', to='marketplace.institution'),
        ),
        migrations.AlterField(
            model_name='adlisting',
            name='price',
            field=models.CharField(blank=True, default='-', help_text='Allow this empty for free products or services or if the price is in the advert description.', max_length=20, null=True, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='itemlisting',
            name='duration',
            field=models.DurationField(choices=[(datetime.timedelta(days=3), '3 days'), (datetime.timedelta(days=5), '5 days'), (datetime.timedelta(days=7), '1 week'), (datetime.timedelta(days=10), '10 days'), (datetime.timedelta(days=28), '1 month')], default=datetime.timedelta(days=28), help_text='For how long should your post be available'),
        ),
    ]
