# Generated by Django 3.1.3 on 2021-03-22 00:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_auto_20210218_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='bookmarkers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookmarked_ads', related_query_name='bookmarked_ad', to='marketplace.marketplaceprofile'),
        ),
        migrations.AddField(
            model_name='institution',
            name='datetime_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='bookmarkers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookmarked_posts', related_query_name='bookmarked_post', to='marketplace.marketplaceprofile'),
        ),
    ]
