# Generated by Django 3.1.3 on 2021-08-21 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_auto_20210820_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adlisting',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ad_listings', related_query_name='ad_listing', to='marketplace.adcategory'),
        ),
    ]
