# Generated by Django 3.1.3 on 2021-03-22 02:56

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_auto_20210322_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='category_en',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='marketplace.category'),
        ),
        migrations.AddField(
            model_name='ad',
            name='category_fr',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='marketplace.category'),
        ),
        migrations.AddField(
            model_name='ad',
            name='description_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='description_fr',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='institution_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ad_posts', related_query_name='post', to='marketplace.institution'),
        ),
        migrations.AddField(
            model_name='ad',
            name='institution_fr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ad_posts', related_query_name='post', to='marketplace.institution'),
        ),
        migrations.AddField(
            model_name='ad',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French')], default='en', max_length=3, verbose_name='Language'),
        ),
        migrations.AddField(
            model_name='ad',
            name='slug_en',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='slug_fr',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='title_en',
            field=models.CharField(max_length=30, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='ad',
            name='title_fr',
            field=models.CharField(max_length=30, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='category',
            name='group_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='marketplace.parentcategory', verbose_name='Group'),
        ),
        migrations.AddField(
            model_name='category',
            name='group_fr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='marketplace.parentcategory', verbose_name='Group'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=35, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_fr',
            field=models.CharField(max_length=35, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='item',
            name='category_en',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='marketplace.category'),
        ),
        migrations.AddField(
            model_name='item',
            name='category_fr',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='marketplace.category'),
        ),
        migrations.AddField(
            model_name='item',
            name='condition_description_en',
            field=models.TextField(help_text='Provide details about the condition of a non brand new item, including any defects of flaws, so that buyers know exactly what to expect.', null=True, verbose_name='Condition description'),
        ),
        migrations.AddField(
            model_name='item',
            name='condition_description_fr',
            field=models.TextField(help_text='Provide details about the condition of a non brand new item, including any defects of flaws, so that buyers know exactly what to expect.', null=True, verbose_name='Condition description'),
        ),
        migrations.AddField(
            model_name='item',
            name='description_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='description_fr',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='institution_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_posts', related_query_name='post', to='marketplace.institution'),
        ),
        migrations.AddField(
            model_name='item',
            name='institution_fr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_posts', related_query_name='post', to='marketplace.institution'),
        ),
        migrations.AddField(
            model_name='item',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French')], default='en', max_length=3, verbose_name='Language'),
        ),
        migrations.AddField(
            model_name='item',
            name='slug_en',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='slug_fr',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='title_en',
            field=models.CharField(max_length=30, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='item',
            name='title_fr',
            field=models.CharField(max_length=30, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='datetime_added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date/time added'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='ad',
            name='number_of_bookmarks',
            field=models.PositiveIntegerField(default=0, verbose_name='Number of bookmarks'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='title',
            field=models.CharField(max_length=30, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='category',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='marketplace.parentcategory', verbose_name='Group'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=35, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='datetime_added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date/time added'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='location',
            field=models.CharField(help_text='Street or quarter where institution is located', max_length=20, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='name',
            field=models.CharField(max_length=40, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='item',
            name='condition_description',
            field=models.TextField(help_text='Provide details about the condition of a non brand new item, including any defects of flaws, so that buyers know exactly what to expect.', verbose_name='Condition description'),
        ),
        migrations.AlterField(
            model_name='item',
            name='datetime_added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date/time added'),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='number_of_bookmarks',
            field=models.PositiveIntegerField(default=0, verbose_name='Number of bookmarks'),
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(max_length=30, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='marketplaceprofile',
            name='credit_points',
            field=models.PositiveIntegerField(default=5, verbose_name='Credit points'),
        ),
        migrations.AlterField(
            model_name='parentcategory',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='can_whatsapp',
            field=models.BooleanField(default=False, verbose_name='Works with WhatsApp'),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='operator',
            field=models.CharField(choices=[('MTN', 'MTN'), ('Nexttel', 'Nexttel'), ('Orange', 'Orange'), ('CAMTEL', 'CAMTEL'), ('O', 'Other')], default='MTN', max_length=8, verbose_name='Operator'),
        ),
    ]
