# Generated by Django 3.1.3 on 2021-11-03 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_auto_20211101_0400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemlisting',
            name='condition_description',
            field=models.TextField(blank=True, default='', help_text='Provide details about the condition of a non brand-new item, including any defects or flaws, so that buyers know exactly what to expect.', verbose_name='Condition description'),
            preserve_default=False,
        ),
    ]
