# Generated by Django 3.1.3 on 2021-08-28 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_auto_20210821_0441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemlistingphoto',
            name='title',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
