# Generated by Django 3.1.3 on 2021-03-22 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_auto_20210322_0256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='category_en',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='category_fr',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='institution_en',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='institution_fr',
        ),
        migrations.RemoveField(
            model_name='category',
            name='group_en',
        ),
        migrations.RemoveField(
            model_name='category',
            name='group_fr',
        ),
        migrations.RemoveField(
            model_name='item',
            name='category_en',
        ),
        migrations.RemoveField(
            model_name='item',
            name='category_fr',
        ),
        migrations.RemoveField(
            model_name='item',
            name='institution_en',
        ),
        migrations.RemoveField(
            model_name='item',
            name='institution_fr',
        ),
        migrations.AddField(
            model_name='institution',
            name='name_en',
            field=models.CharField(max_length=40, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='institution',
            name='name_fr',
            field=models.CharField(max_length=40, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='parentcategory',
            name='name_en',
            field=models.CharField(max_length=30, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='parentcategory',
            name='name_fr',
            field=models.CharField(max_length=30, null=True, verbose_name='Name'),
        ),
    ]
