# Generated by Django 3.1.3 on 2021-08-28 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210828_1947'),
        ('marketplace', '0005_auto_20210828_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='adlisting',
            name='contact_numbers',
            field=models.ManyToManyField(related_name='_adlisting_contact_numbers_+', to='users.PhoneNumber'),
        ),
        migrations.AddField(
            model_name='adlistingphoto',
            name='title',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='itemlisting',
            name='contact_numbers',
            field=models.ManyToManyField(related_name='_itemlisting_contact_numbers_+', to='users.PhoneNumber'),
        ),
        migrations.AlterField(
            model_name='itemlistingphoto',
            name='title',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
