# Generated by Django 3.1.3 on 2021-08-30 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_auto_20210828_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adlisting',
            name='price',
            field=models.CharField(blank=True, default='-', help_text='Allow this empty for free products and services or if the price is in the advert description.', max_length=20, null=True, verbose_name='Price'),
        ),
    ]
