# Generated by Django 3.1.3 on 2021-08-30 20:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_auto_20210830_1942'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adlistingphoto',
            old_name='image',
            new_name='file',
        ),
        migrations.AddField(
            model_name='adlistingphoto',
            name='upload_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
