# Generated by Django 3.1.3 on 2021-08-31 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0008_auto_20210830_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adlisting',
            name='price',
        ),
        migrations.AddField(
            model_name='adlisting',
            name='pricing',
            field=models.CharField(blank=True, default='-', help_text='Allow this empty for free products and services or if the pricing is in the advert description.', max_length=20, null=True, verbose_name='Pricing'),
        ),
    ]
