# Generated by Django 3.1.3 on 2021-07-27 13:25

import core.model_fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0008_auto_20210726_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='contact_email',
            field=core.model_fields.LowerCaseEmailField(default='default@email.com', help_text='Email address to use for notifications', max_length=50, validators=[django.core.validators.EmailValidator()], verbose_name='Email address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemlisting',
            name='contact_email',
            field=core.model_fields.LowerCaseEmailField(default='default@email.com', help_text='Email address to use for notifications', max_length=50, validators=[django.core.validators.EmailValidator()], verbose_name='Email address'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='AdPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ad photos')),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', related_query_name='image', to='marketplace.ad')),
            ],
        ),
    ]
