# Generated by Django 3.1.3 on 2021-11-24 22:55

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0009_auto_20211114_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adlistingphoto',
            name='file',
            field=easy_thumbnails.fields.ThumbnailerImageField(height_field='height', upload_to='ad_photos/', width_field='width'),
        ),
        migrations.AlterField(
            model_name='itemlistingphoto',
            name='file',
            field=easy_thumbnails.fields.ThumbnailerImageField(height_field='height', upload_to='item_photos/', width_field='width'),
        ),
    ]
