# Generated by Django 3.1.3 on 2021-09-01 20:53

import core.model_fields
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0010_auto_20210901_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adlisting',
            name='contact_email',
            field=core.model_fields.LowerCaseEmailField(help_text='Email address to contact; enter a valid email', max_length=50, validators=[django.core.validators.EmailValidator()], verbose_name='Email address'),
        ),
        migrations.AlterField(
            model_name='itemlisting',
            name='contact_email',
            field=core.model_fields.LowerCaseEmailField(help_text='Email address to contact; enter a valid email', max_length=50, validators=[django.core.validators.EmailValidator()], verbose_name='Email address'),
        ),
    ]
