# Generated by Django 3.1.3 on 2021-07-29 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0010_auto_20210728_0251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='subtitle_en',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='subtitle_fr',
        ),
        migrations.RemoveField(
            model_name='itemlisting',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='itemlisting',
            name='subtitle_en',
        ),
        migrations.RemoveField(
            model_name='itemlisting',
            name='subtitle_fr',
        ),
        migrations.AlterField(
            model_name='itemlisting',
            name='price',
            field=models.PositiveIntegerField(help_text='Figures and spaces only, no commas or dots. <br> Enter <b>0</b> for free products or services.', verbose_name='Price'),
        ),
    ]
