# Generated by Django 3.1.3 on 2021-07-29 02:51

import core.model_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0011_auto_20210729_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='location',
            field=models.CharField(help_text='Street or quarter where institution is located', max_length=40, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='name',
            field=core.model_fields.TitleCaseField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='name_en',
            field=core.model_fields.TitleCaseField(max_length=50, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='name_fr',
            field=core.model_fields.TitleCaseField(max_length=50, null=True, verbose_name='Name'),
        ),
    ]
