# Generated by Django 3.1.3 on 2021-09-08 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0011_auto_20210901_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemlisting',
            name='condition',
            field=models.CharField(choices=[('N', 'New'), ('U', 'Used'), ('D', 'Defective(some parts are not working)')], default='N', help_text="Select the condition of the item you're listing.", max_length=3),
        ),
    ]
