# Generated by Django 3.1.3 on 2021-07-29 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0013_auto_20210729_0300'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemSubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35, verbose_name='Name')),
                ('name_en', models.CharField(max_length=35, null=True, verbose_name='Name')),
                ('name_fr', models.CharField(max_length=35, null=True, verbose_name='Name')),
            ],
            options={
                'verbose_name_plural': 'Item Categories',
            },
        ),
        migrations.AlterModelOptions(
            name='itemcategory',
            options={'verbose_name_plural': 'Item Parent Categories'},
        ),
        migrations.RemoveField(
            model_name='itemcategory',
            name='parent_category',
        ),
        migrations.AlterField(
            model_name='itemcategory',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='itemcategory',
            name='name_en',
            field=models.CharField(max_length=30, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='itemcategory',
            name='name_fr',
            field=models.CharField(max_length=30, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='itemlisting',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item_listings', related_query_name='item_listing', to='marketplace.itemcategory'),
        ),
        migrations.DeleteModel(
            name='ItemParentCategory',
        ),
        migrations.AddField(
            model_name='itemsubcategory',
            name='parent_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sub_categories', related_query_name='sub_category', to='marketplace.itemcategory'),
        ),
    ]
