# Generated by Django 3.1.3 on 2021-07-30 03:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0015_auto_20210729_0421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemlistingphoto',
            name='image',
        ),
        migrations.AddField(
            model_name='itemlistingphoto',
            name='file',
            field=models.ImageField(default='none?', upload_to='item_photos/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemlistingphoto',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemlistingphoto',
            name='upload_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itemlistingphoto',
            name='item_listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', related_query_name='image', to='marketplace.itemlisting'),
        ),
    ]
