# Generated by Django 3.1.3 on 2021-09-13 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0015_auto_20210912_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='adlisting',
            name='updated_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='itemlisting',
            name='updated_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
