# Generated by Django 3.1.3 on 2021-09-17 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0017_auto_20210913_2058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adlisting',
            old_name='updated_datetime',
            new_name='last_modified',
        ),
        migrations.RenameField(
            model_name='itemlisting',
            old_name='updated_datetime',
            new_name='last_modified',
        ),
        migrations.AddField(
            model_name='adlisting',
            name='bookmark_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='itemlisting',
            name='bookmark_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
