# Generated by Django 3.1.3 on 2021-09-17 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0018_auto_20210917_1410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adlisting',
            name='bookmark_count',
        ),
        migrations.RemoveField(
            model_name='itemlisting',
            name='bookmark_count',
        ),
    ]
