# Generated by Django 3.1.3 on 2021-09-25 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0019_auto_20210917_1430'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adlisting',
            old_name='owner',
            new_name='poster',
        ),
        migrations.RenameField(
            model_name='itemlisting',
            old_name='owner',
            new_name='poster',
        ),
        migrations.RemoveField(
            model_name='adlisting',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='itemlisting',
            name='duration',
        ),
    ]
