# Generated by Django 3.1.3 on 2021-08-04 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0019_auto_20210803_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adphoto',
            name='ad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', related_query_name='photo', to='marketplace.ad'),
        ),
        migrations.AlterField(
            model_name='adphoto',
            name='image',
            field=models.ImageField(upload_to='ad_photos/'),
        ),
        migrations.AlterField(
            model_name='itemlistingphoto',
            name='item_listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', related_query_name='photo', to='marketplace.itemlisting'),
        ),
    ]
