# Generated by Django 3.1.3 on 2021-09-25 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0020_auto_20210925_0531'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemsubcategory',
            options={'verbose_name_plural': 'Item SubCategories'},
        ),
        migrations.AddField(
            model_name='adcategory',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='itemsubcategory',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='adlisting',
            name='original_language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French')], editable=False, help_text='Language in which post was created', max_length=2),
        ),
        migrations.AlterField(
            model_name='itemlisting',
            name='original_language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French')], editable=False, help_text='Language in which post was created', max_length=2),
        ),
    ]
