# Generated by Django 3.1.3 on 2021-08-04 01:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketplace', '0020_auto_20210804_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', related_query_name='ad', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='itemlisting',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_listings', related_query_name='item_listing', to=settings.AUTH_USER_MODEL),
        ),
    ]
