# Generated by Django 3.1.3 on 2021-09-26 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0021_auto_20210925_0541'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemlisting',
            old_name='institution',
            new_name='school',
        ),
        migrations.RemoveField(
            model_name='adlisting',
            name='institution',
        ),
        migrations.AddField(
            model_name='adlisting',
            name='school',
            field=models.ForeignKey(blank=True, help_text='Allow this empty if this advert concerns no particular school.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ad_listings', related_query_name='ad_listing', to='marketplace.institution'),
        ),
    ]
