# Generated by Django 3.1.3 on 2021-08-05 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0021_auto_20210804_0139'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemlisting',
            name='sub_category',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, related_name='item_listings', related_query_name='item_listing', to='marketplace.itemsubcategory'),
            preserve_default=False,
        ),
    ]
