# Generated by Django 3.1.3 on 2021-09-30 01:18

import core.model_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0022_auto_20210926_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='adlisting',
            name='contact_email',
            field=core.model_fields.NormalizedEmailField(help_text='Email address to contact; enter a valid email', max_length=50, verbose_name='Email address'),
        ),
        migrations.AlterField(
            model_name='adlisting',
            name='pricing',
            field=models.CharField(blank=True, default='-', help_text='Allow this empty for free products and services or if the pricing is in the advert description.', max_length=40, null=True, verbose_name='Pricing'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='location',
            field=models.CharField(help_text='Street or quarter where institution is located', max_length=60, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='itemlisting',
            name='contact_email',
            field=core.model_fields.NormalizedEmailField(help_text='Email address to contact; enter a valid email', max_length=50, verbose_name='Email address'),
        ),
    ]
