# Generated by Django 3.1.3 on 2021-08-07 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0022_itemlisting_sub_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemlisting',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='item_listings', related_query_name='item_listing', to='marketplace.itemsubcategory'),
        ),
    ]
