# Generated by Django 3.1.3 on 2021-09-30 04:24

import core.model_fields
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0023_auto_20210930_0118'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adlisting',
            options={'ordering': ['-posted_datetime']},
        ),
        migrations.AlterModelOptions(
            name='itemlisting',
            options={'ordering': ['-posted_datetime'], 'verbose_name_plural': 'Item Listings'},
        ),
        migrations.RemoveIndex(
            model_name='adlisting',
            name='marketplace_datetim_5cd968_idx',
        ),
        migrations.RemoveIndex(
            model_name='itemlisting',
            name='marketplace_datetim_e4838d_idx',
        ),
        migrations.RemoveField(
            model_name='adlisting',
            name='datetime_added',
        ),
        migrations.RemoveField(
            model_name='itemlisting',
            name='datetime_added',
        ),
        migrations.AddField(
            model_name='adlisting',
            name='posted_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adlisting',
            name='pricing_en',
            field=models.CharField(default='-', help_text='Allow this empty for free products and services or if the pricing is in the advert description.', max_length=40, null=True, verbose_name='Pricing'),
        ),
        migrations.AddField(
            model_name='adlisting',
            name='pricing_fr',
            field=models.CharField(default='-', help_text='Allow this empty for free products and services or if the pricing is in the advert description.', max_length=40, null=True, verbose_name='Pricing'),
        ),
        migrations.AddField(
            model_name='itemlisting',
            name='posted_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adlisting',
            name='contact_email',
            field=core.model_fields.LowerCaseEmailField(help_text='Email address to contact; enter a valid email.', max_length=50, validators=[django.core.validators.EmailValidator()], verbose_name='Email address'),
        ),
        migrations.AlterField(
            model_name='adlisting',
            name='contact_name',
            field=core.model_fields.TitleCaseField(help_text='Please use your real names.', max_length=25, verbose_name='Full name'),
        ),
        migrations.AlterField(
            model_name='adlisting',
            name='pricing',
            field=models.CharField(default='-', help_text='Allow this empty for free products and services or if the pricing is in the advert description.', max_length=40, verbose_name='Pricing'),
        ),
        migrations.AlterField(
            model_name='itemlisting',
            name='contact_email',
            field=core.model_fields.LowerCaseEmailField(help_text='Email address to contact; enter a valid email.', max_length=50, validators=[django.core.validators.EmailValidator()], verbose_name='Email address'),
        ),
        migrations.AlterField(
            model_name='itemlisting',
            name='contact_name',
            field=core.model_fields.TitleCaseField(help_text='Please use your real names.', max_length=25, verbose_name='Full name'),
        ),
        migrations.AddIndex(
            model_name='adlisting',
            index=models.Index(fields=['-posted_datetime'], name='marketplace_posted__0a118c_idx'),
        ),
        migrations.AddIndex(
            model_name='itemlisting',
            index=models.Index(fields=['-posted_datetime'], name='marketplace_posted__8b2114_idx'),
        ),
    ]
