# Generated by Django 3.1.3 on 2021-08-09 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0023_auto_20210807_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='price',
            field=models.PositiveIntegerField(default=0, help_text='Figures and spaces only, no commas or dots. <br> Enter <b>-</b> for free products or services, or if the price is in the advert description.', verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='slug',
            field=models.SlugField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ad',
            name='slug_en',
            field=models.SlugField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='slug_fr',
            field=models.SlugField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='itemlisting',
            name='slug',
            field=models.SlugField(max_length=255),
        ),
        migrations.AlterField(
            model_name='itemlisting',
            name='slug_en',
            field=models.SlugField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='itemlisting',
            name='slug_fr',
            field=models.SlugField(max_length=255, null=True),
        ),
    ]
