# Generated by Django 3.1.3 on 2021-08-09 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0024_auto_20210809_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='name_en',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='name_fr',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Name'),
        ),
    ]
