# Generated by Django 3.1.3 on 2021-10-02 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requested_items', '0005_auto_20211002_1828'),
        ('lost_and_found', '0018_auto_20211002_1828'),
        ('socialize', '0013_auto_20211002_1828'),
        ('qa_site', '0020_auto_20211002_1828'),
        ('past_papers', '0016_auto_20211002_1828'),
        ('core', '0007_institution'),
        ('marketplace', '0024_auto_20210930_0424'),
    ]

    operations = [
        migrations.AddField(
            model_name='adlisting',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='itemlisting',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='adlisting',
            name='school',
            field=models.ForeignKey(blank=True, help_text='Allow this empty if this advert concerns no particular school.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ad_listings', related_query_name='ad_listing', to='core.institution'),
        ),
        migrations.AlterField(
            model_name='itemlisting',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_listings', related_query_name='item_listing', to='core.institution'),
        ),
        migrations.DeleteModel(
            name='Institution',
        ),
    ]
