# Generated by Django 3.1.3 on 2021-08-11 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0025_auto_20210809_2311'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['-datetime_added'], name='marketplace_datetim_7cf7f2_idx'),
        ),
        migrations.AddIndex(
            model_name='itemlisting',
            index=models.Index(fields=['-datetime_added'], name='marketplace_datetim_e4838d_idx'),
        ),
    ]
