# Generated by Django 3.1.3 on 2021-10-08 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0026_auto_20211007_0128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adlisting',
            name='contact_name',
        ),
        migrations.RemoveField(
            model_name='itemlisting',
            name='contact_name',
        ),
    ]
