# Generated by Django 3.1.3 on 2021-10-18 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost_or_found', '0002_auto_20211017_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostitem',
            name='bounty',
            field=models.CharField(blank=True, default='', help_text='Award/bounty given to the person who will return the item. Make sure that you are in possession of the award. <br> This is optional but can be used as motivation.', max_length=100, verbose_name='Bounty'),
            preserve_default=False,
        ),
    ]
