# Generated by Django 3.1.3 on 2021-10-30 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost_or_found', '0003_auto_20211018_0340'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='founditem',
            name='lost_and_fo_posted__5efadc_idx',
        ),
        migrations.RemoveIndex(
            model_name='lostitem',
            name='lost_and_fo_posted__ae3e94_idx',
        ),
        migrations.AddIndex(
            model_name='founditem',
            index=models.Index(fields=['-posted_datetime'], name='lost_or_fou_posted__4c19c6_idx'),
        ),
        migrations.AddIndex(
            model_name='lostitem',
            index=models.Index(fields=['-posted_datetime'], name='lost_or_fou_posted__681bbd_idx'),
        ),
    ]
