# Generated by Django 3.1.3 on 2021-08-20 09:41

import core.model_fields
import datetime
from django.conf import settings
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketplace', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', core.model_fields.NormalizedEmailField(error_messages={'unique': 'A user with that email already exists.'}, help_text='We will send a verification code to this email', max_length=50, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='Email address')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='This name will be used in the questions/answers site, you can always change it later.', max_length=15, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='Username')),
                ('full_name', models.CharField(help_text='Two of your names will be okay. Please enter your real names.', max_length=25, validators=[], verbose_name='Full name')),
                ('first_language', models.CharField(choices=[('en', 'English'), ('fr', 'French')], default='fr', help_text="Your preferred language. Don't worry, you can always view the site in another language.", max_length=3, verbose_name='First language')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=2, verbose_name='Gender')),
                ('site_points', models.PositiveIntegerField(default=5, verbose_name='Site points')),
                ('status', models.CharField(choices=[('A', 'active'), ('D', 'deleted'), ('S', 'suspended')], default='A', max_length=2)),
                ('deactivation_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Deactivation date/time')),
                ('datetime_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date/time joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='Last login')),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_mod', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('bookmarked_ad_listings', models.ManyToManyField(related_name='bookmarkers', related_query_name='bookmarker', to='marketplace.AdListing')),
                ('bookmarked_item_listings', models.ManyToManyField(related_name='bookmarkers', related_query_name='bookmarker', to='marketplace.ItemListing')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Suspension',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
                ('duration', models.DurationField(default=datetime.timedelta(days=1))),
                ('is_active', models.BooleanField(default=True)),
                ('reason', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suspensions', related_query_name='suspension', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(choices=[('MTN', 'MTN'), ('Nexttel', 'Nexttel'), ('Orange', 'Orange'), ('CAMTEL', 'CAMTEL'), ('O', 'Other')], default='MTN', max_length=8, verbose_name='Operator')),
                ('number', models.CharField(help_text='Enter mobile number <b>(without +237)</b>', max_length=20, verbose_name='Phone number')),
                ('can_whatsapp', models.BooleanField(default=False, verbose_name='Works with WhatsApp')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Phone Number',
                'verbose_name_plural': 'Phone Numbers',
            },
        ),
    ]
