# Generated by Django 3.1.3 on 2021-08-28 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonenumber',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='phonenumber',
            name='object_id',
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', related_query_name='phone_number', to='users.user'),
            preserve_default=False,
        ),
    ]
