# Generated by Django 3.1.3 on 2021-03-22 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French')], default='en', help_text='Your preferred language', max_length=3, verbose_name='First language'),
        ),
    ]
