# Generated by Django 3.1.3 on 2021-09-04 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210828_1947'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['-site_points'], name='users_user_site_po_4a5979_idx'),
        ),
    ]
