# Generated by Django 3.1.3 on 2021-03-22 15:46

from django.db import migrations, models
import django.utils.timezone
import core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_first_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='datetime_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date/time joined'),
        ),
        migrations.AlterField(
            model_name='user',
            name='deletion_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deletion date/time'),
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, default='Default Name', help_text='Two of your names will be okay.', max_length=25, validators=[core.validators.validate_full_name], verbose_name='Full name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(auto_now=True, verbose_name='Last login'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists'}, help_text='This is the name people will know you by on this site. You can always change it later', max_length=15, unique=True, verbose_name='Username'),
        ),
    ]
