# Generated by Django 3.1.3 on 2021-03-22 16:57

from django.db import migrations, models
import users.validators

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210322_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'A user with that email already exists'}, help_text='We will send a verification code to this email', max_length=50, unique=True, verbose_name='Email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, help_text='Two of your names will be okay. Please enter your real names.', max_length=25, validators=[users.validators.validate_full_name], verbose_name='Full name'),
        ),
    ]
