# Generated by Django 3.1.3 on 2021-03-23 14:42

import core.model_fields
import core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210322_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=core.model_fields.LowerCaseEmailField(error_messages={'unique': 'A user with that email already exists'}, help_text='We will send a verification code to this email', max_length=50, unique=True, verbose_name='Email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=core.model_fields.TitleCaseField(blank=True, help_text='Two of your names will be okay. Please enter your real names.', max_length=25, validators=[core.validators.validate_full_name], verbose_name='Full name'),
        ),
    ]
