# Generated by Django 3.1.3 on 2021-09-13 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210905_0056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bookmarked_ad_listings',
        ),
        migrations.RemoveField(
            model_name='user',
            name='bookmarked_item_listings',
        ),
        migrations.AlterField(
            model_name='user',
            name='site_points',
            field=models.PositiveIntegerField(default=5, editable=False, verbose_name='Site points'),
        ),
    ]
