# Generated by Django 3.1.3 on 2021-07-14 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210323_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists'}, help_text='This is the name by which people will know you on this site. You can always change it later', max_length=15, unique=True, verbose_name='Username'),
        ),
    ]
