# Generated by Django 3.1.3 on 2021-09-14 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210913_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='datetime_joined',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date/time joined'),
        ),
        migrations.AlterField(
            model_name='user',
            name='deactivation_datetime',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Deactivation date/time'),
        ),
        migrations.DeleteModel(
            name='Suspension',
        ),
    ]
