# Generated by Django 3.1.3 on 2021-09-27 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210914_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='previous_points',
            field=models.PositiveIntegerField(default=10, editable=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='site_points',
            field=models.PositiveIntegerField(default=10, editable=False, verbose_name='Site points'),
        ),
    ]
