# Generated by Django 3.1.3 on 2021-07-15 00:56

import core.model_fields
import users.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210714_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='site_points',
            field=models.PositiveIntegerField(default=5, verbose_name='Site points'),
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=core.model_fields.TitleCaseField(help_text='Two of your names will be okay. Please enter your real names.', max_length=25, validators=[users.validators.validate_full_name], verbose_name='Full name'),
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(choices=[('MTN', 'MTN'), ('Nexttel', 'Nexttel'), ('Orange', 'Orange'), ('CAMTEL', 'CAMTEL'), ('O', 'Other')], default='MTN', max_length=8, verbose_name='Operator')),
                ('number', models.CharField(help_text='Enter mobile number <b>(without +237)</b>', max_length=9, validators=[users.validators.validate_tel_number], verbose_name='Phone number')),
                ('can_whatsapp', models.BooleanField(default=False, verbose_name='Works with WhatsApp')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', related_query_name='phone_number', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
