# Generated by Django 3.1.3 on 2021-09-28 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210927_2051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='previous_points',
        ),
    ]
