# Generated by Django 3.1.3 on 2021-07-16 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210715_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists'}, help_text='This name will be used in the questions/answers site. You can always change it later', max_length=15, unique=True, verbose_name='Username'),
        ),
    ]
