# Generated by Django 3.1.3 on 2021-07-16 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210716_0359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French')], default='en', help_text="Your preferred language. Don't worry, you can always view the site in another language.", max_length=3, verbose_name='First language'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists'}, help_text='This name will be used in the questions/answers site, you can always change it later.', max_length=15, unique=True, verbose_name='Username'),
        ),
    ]
