# Generated by Django 3.1.3 on 2021-07-18 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210716_0450'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, help_text='This will be used to filter results in the <b>Socialize</b> site.', null=True, verbose_name='Date of birth'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=2, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French')], default='fr', help_text="Your preferred language. Don't worry, you can always view the site in another language.", max_length=3, verbose_name='First language'),
        ),
    ]
