# Generated by Django 3.1.3 on 2021-10-02 18:28

from django.db import migrations, models
import core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20211002_0456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(help_text='Two of your names will be okay. Please enter your real names.', max_length=25, validators=[core.validators.FullNameValidator()], verbose_name='Full name'),
        ),
    ]
