# Generated by Django 3.1.3 on 2021-10-02 18:28

import core.model_fields
from django.db import migrations
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20211002_0456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=core.model_fields.FullNameField(help_text='Two of your names will be okay. Please enter your real names.', max_length=25, validators=[users.validators.FullNameValidator()], verbose_name='Full name'),
        ),
    ]
