# Generated by Django 3.1.3 on 2021-07-19 13:14

import core.model_fields
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20210718_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=core.model_fields.LowerCaseEmailField(error_messages={'unique': 'A user with that email already exists'}, help_text='We will send a verification code to this email', max_length=50, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='Email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists'}, help_text='This name will be used in the questions/answers site, you can always change it later.', max_length=15, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='Username'),
        ),
    ]
