# Generated by Django 3.1.3 on 2021-10-06 04:11

from django.db import migrations, models
import core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20211003_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(help_text='Enter a valid full name. It should be two or three of your names separated by a spaceand each name may contain only letters or hyphens.', max_length=25, validators=[core.validators.FullNameValidator()], verbose_name='Full name'),
        ),
    ]
