# Generated by Django 3.1.3 on 2021-07-22 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_user_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumber',
            name='number',
            field=models.CharField(help_text='Enter mobile number <b>(without +237)</b>', max_length=9, verbose_name='Phone number'),
        ),
    ]
