# Generated by Django 3.1.3 on 2021-10-07 01:28

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20211006_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French')], default='en', help_text="Your preferred language. Don't worry, you can always view the site in another language.", max_length=3, verbose_name='First language'),
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(help_text='Enter a valid full name. It should be two or three of your names separated by a space and each name may contain only letters or hyphens. <br>No name should start or end with a hyphen, and no name should contain only hyphens.', max_length=25, validators=[core.validators.FullNameValidator()], verbose_name='Full name'),
        ),
    ]
