# Generated by Django 3.1.3 on 2021-10-08 04:55

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20211007_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Your username should be between 4 to 15 characters and the first 4 characters must be letters. <br> It should not contain any symbols, dashes or spaces. <br>All other characters are allowed (letters, numbers, hyphens and underscores).', max_length=15, unique=True, validators=[core.validators.UsernameValidator()], verbose_name='Username'),
        ),
    ]
