# Generated by Django 3.1.3 on 2021-08-10 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20210728_0251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='deletion_datetime',
        ),
        migrations.AddField(
            model_name='user',
            name='deactivation_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deactivation date/time'),
        ),
    ]
