# Generated by Django 3.1.3 on 2021-11-01 04:00

from django.db import migrations, models
import django.template.defaultfilters


class Migration(migrations.Migration):

    dependencies = [
        ('lost_or_found', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='founditem',
            name='item_found',
            field=models.CharField(help_text='What have you found?', max_length=100, unique=django.template.defaultfilters.truncatewords, verbose_name='Item found'),
        ),
        migrations.AlterField(
            model_name='founditem',
            name='item_found_en',
            field=models.CharField(help_text='What have you found?', max_length=100, null=True, unique=django.template.defaultfilters.truncatewords, verbose_name='Item found'),
        ),
        migrations.AlterField(
            model_name='founditem',
            name='item_found_fr',
            field=models.CharField(help_text='What have you found?', max_length=100, null=True, unique=django.template.defaultfilters.truncatewords, verbose_name='Item found'),
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='item_lost',
            field=models.CharField(help_text='What have you lost?', max_length=100, unique=True, verbose_name='Item lost'),
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='item_lost_en',
            field=models.CharField(help_text='What have you lost?', max_length=100, null=True, unique=True, verbose_name='Item lost'),
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='item_lost_fr',
            field=models.CharField(help_text='What have you lost?', max_length=100, null=True, unique=True, verbose_name='Item lost'),
        ),
    ]
