# Generated by Django 3.1.3 on 2021-11-13 07:06

import core.model_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lost_or_found', '0002_auto_20211101_0400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostitemphoto',
            name='file',
            field=core.model_fields.DynamicStorageFileField(upload_to='lost_items_photos/'),
        ),
    ]
