# Generated by Django 3.2 on 2022-07-27 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20220724_2245'),
        ('lost_or_found', '0009_auto_20220714_0425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='founditem',
            name='school',
        ),
        migrations.RemoveField(
            model_name='lostitem',
            name='school',
        ),
        migrations.AddField(
            model_name='founditem',
            name='city',
            field=models.ForeignKey(default=1, help_text='City where item was found', on_delete=django.db.models.deletion.CASCADE, related_name='found_items', related_query_name='found_item', to='core.city'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lostitem',
            name='city',
            field=models.ForeignKey(default=1, help_text='City where item was lost', on_delete=django.db.models.deletion.CASCADE, related_name='lost_items', related_query_name='lost_item', to='core.city'),
            preserve_default=False,
        ),
    ]
