# Generated by Django 3.2 on 2022-09-28 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lost_or_found', '0012_auto_20220928_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='LostItemBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookmark_datetime', models.DateTimeField(auto_now_add=True)),
                ('bookmarker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lost_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='lost_or_found.lostitem')),
            ],
        ),
        migrations.CreateModel(
            name='FoundItemBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookmark_datetime', models.DateTimeField(auto_now_add=True)),
                ('bookmarker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('found_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='lost_or_found.founditem')),
            ],
        ),
        # Manually dropped the previous m2m tables that were in the db 
        # and replaced migrations.AlterField to AddField.
        migrations.AddField(
            model_name='founditem',
            name='bookmarkers',
            field=models.ManyToManyField(blank=True, related_name='bookmarked_found_items', related_query_name='bookmarked_found_item', through='lost_or_found.FoundItemBookmark', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lostitem',
            name='bookmarkers',
            field=models.ManyToManyField(blank=True, related_name='bookmarked_lost_items', related_query_name='bookmarked_lost_item', through='lost_or_found.LostItemBookmark', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='lostitembookmark',
            constraint=models.UniqueConstraint(fields=('lost_item', 'bookmarker'), name='unique_lost_item_bookmark'),
        ),
        migrations.AddConstraint(
                model_name='founditembookmark',
                constraint=models.UniqueConstraint(fields=('found_item', 'bookmarker'), name='unique_found_item_bookmark'),
            ),
    ]
