# Generated by Django 3.2 on 2022-09-28 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost_or_found', '0013_auto_20220928_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='founditem',
            name='item_found',
            field=models.CharField(help_text='What have you found?', max_length=100, verbose_name='Item found'),
        ),
        migrations.AlterField(
            model_name='founditem',
            name='item_found_en',
            field=models.CharField(help_text='What have you found?', max_length=100, null=True, verbose_name='Item found'),
        ),
        migrations.AlterField(
            model_name='founditem',
            name='item_found_fr',
            field=models.CharField(help_text='What have you found?', max_length=100, null=True, verbose_name='Item found'),
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='item_lost',
            field=models.CharField(help_text='What have you lost?', max_length=100, verbose_name='Item lost'),
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='item_lost_en',
            field=models.CharField(help_text='What have you lost?', max_length=100, null=True, verbose_name='Item lost'),
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='item_lost_fr',
            field=models.CharField(help_text='What have you lost?', max_length=100, null=True, verbose_name='Item lost'),
        ),
    ]
