# Generated by Django 3.1.3 on 2021-02-18 23:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hitcount', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hit',
            name='user',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='hitcount',
            unique_together={('content_type', 'object_id')},
        ),
    ]
