# Generated by Django 3.1.3 on 2021-07-27 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hitcount', '0002_auto_20210218_2343'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hit',
            options={'get_latest_by': 'created', 'ordering': ('-created',), 'verbose_name': 'Hit', 'verbose_name_plural': 'Hits'},
        ),
        migrations.AlterModelOptions(
            name='hitcount',
            options={'get_latest_by': 'modified', 'verbose_name': 'Hit count', 'verbose_name_plural': 'Hit counts'},
        ),
    ]
