# Generated by Django 3.1.3 on 2021-10-17 22:43

import core.storage_backends
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('socialize', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialProfile',
            fields=[
                ('level', models.CharField(choices=[('O', 'Ordinary Level'), ('A', 'Advanced Level'), ('BEPC', 'BEPC'), ('PROB', 'Probatoire'), ('BAC', 'Baccalaureat'), ('BACH', "HND/Bachelor's"), ('BTS', 'BTS'), ('LIC', 'Licence'), ('MS', "Master's"), ('PhD', 'Doctorate')], default='O', max_length=5, verbose_name='Level')),
                ('about_me', models.TextField(blank=True, verbose_name='A little about me')),
                ('about_me_en', models.TextField(blank=True, null=True, verbose_name='A little about me')),
                ('about_me_fr', models.TextField(blank=True, null=True, verbose_name='A little about me')),
                ('hobbies', models.TextField(blank=True, verbose_name='My hobbies and interests')),
                ('hobbies_en', models.TextField(blank=True, null=True, verbose_name='My hobbies and interests')),
                ('hobbies_fr', models.TextField(blank=True, null=True, verbose_name='My hobbies and interests')),
                ('profile_image', models.ImageField(blank=True, storage=core.storage_backends.PublicMediaStorage(), upload_to='profile_pictures/', verbose_name='Profile image')),
                ('birth_date', models.DateField(help_text="Please at least enter the correct birth year. <br>Your birth date and age won't be visible to other users.", verbose_name='Birthday')),
                ('speciality', models.CharField(help_text='Enter your study department or speciality', max_length=30, verbose_name='Speciality')),
                ('speciality_en', models.CharField(help_text='Enter your study department or speciality', max_length=30, null=True, verbose_name='Speciality')),
                ('speciality_fr', models.CharField(help_text='Enter your study department or speciality', max_length=30, null=True, verbose_name='Speciality')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='social_profile', serialize=False, to='users.user')),
                ('current_relationship', models.CharField(choices=[('single', 'Single'), ('dating', 'Dating'), ('engaged', 'Engaged'), ('married', 'Married'), ('undecided', 'Undecided')], default='single', max_length=15, verbose_name='Current relationship')),
                ('interested_relationship', models.CharField(choices=[('none', 'Not interested'), ('chatting', 'Being chat pals'), ('studies', 'Being study pals'), ('clubbing', 'Clubbing this weekend'), ('dating', 'Dating'), ('flirting', 'Flirting'), ('friendship', 'Friendship'), ('hanging_out', 'Hanging out this weekend'), ('marriage', 'Marriage'), ('undecided', 'Undecided')], default='none', max_length=15, verbose_name='Interested relationship')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=2, verbose_name='Gender')),
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('original_language', models.CharField(choices=[('en', 'English'), ('fr', 'French')], editable=False, max_length=2)),
                ('update_language', models.CharField(blank=True, choices=[('en', 'English'), ('fr', 'French')], editable=False, max_length=2)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('bookmarkers', models.ManyToManyField(blank=True, related_name='bookmarked_social_profiles', related_query_name='bookmarked_social_profile', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_profiles', related_query_name='social_profile', to='core.institution', verbose_name='School')),
                ('social_media', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='socialize.socialmediafollow')),
            ],
            options={
                'ordering': ['-creation_datetime'],
            },
        ),
        migrations.AddIndex(
            model_name='socialprofile',
            index=models.Index(fields=['-creation_datetime'], name='socialize_s_creatio_e404ec_idx'),
        ),
    ]
