# Generated by Django 3.1.3 on 2021-11-13 07:06

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialize', '0002_auto_20211017_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialprofile',
            name='profile_image',
            field=core.fields.DynamicStorageFileField(blank=True, upload_to='profile_pictures/', verbose_name='Profile image'),
        ),
    ]
