# Generated by Django 3.1.3 on 2021-11-13 09:31

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialize', '0003_auto_20211113_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialprofile',
            name='profile_image',
            field=core.fields.DynamicStorageImageField(blank=True, upload_to='profile_pictures/', verbose_name='Profile image'),
        ),
    ]
