# Generated by Django 3.2 on 2022-07-14 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialize', '0007_auto_20211124_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmediafollow',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
