# Generated by Django 3.2 on 2022-07-27 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20220724_2245'),
        ('socialize', '0008_alter_socialmediafollow_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialprofile',
            name='level',
        ),
        migrations.RemoveField(
            model_name='socialprofile',
            name='school',
        ),
        migrations.AddField(
            model_name='socialprofile',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='social_profiles', related_query_name='social_profile', to='core.city', verbose_name='City of residence'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='socialprofile',
            name='speciality',
            field=models.CharField(help_text="Enter your speciality. i.e. what you do or what you're good at.", max_length=30, verbose_name='Speciality'),
        ),
        migrations.AlterField(
            model_name='socialprofile',
            name='speciality_en',
            field=models.CharField(help_text="Enter your speciality. i.e. what you do or what you're good at.", max_length=30, null=True, verbose_name='Speciality'),
        ),
        migrations.AlterField(
            model_name='socialprofile',
            name='speciality_fr',
            field=models.CharField(help_text="Enter your speciality. i.e. what you do or what you're good at.", max_length=30, null=True, verbose_name='Speciality'),
        ),
    ]
