# Generated by Django 3.2 on 2022-07-30 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialize', '0009_auto_20220727_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialprofile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('NB', 'Non-binary')], default='M', max_length=2, verbose_name='Gender'),
        ),
    ]
