# Generated by Django 3.2 on 2022-09-28 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialize', '0011_auto_20220928_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialprofile',
            name='about_me',
            field=models.TextField(blank=True, max_length=3000, verbose_name='A little about me'),
        ),
        migrations.AlterField(
            model_name='socialprofile',
            name='about_me_en',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='A little about me'),
        ),
        migrations.AlterField(
            model_name='socialprofile',
            name='about_me_fr',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='A little about me'),
        ),
        migrations.AlterField(
            model_name='socialprofile',
            name='hobbies',
            field=models.TextField(blank=True, max_length=3000, verbose_name='My hobbies and interests'),
        ),
        migrations.AlterField(
            model_name='socialprofile',
            name='hobbies_en',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='My hobbies and interests'),
        ),
        migrations.AlterField(
            model_name='socialprofile',
            name='hobbies_fr',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='My hobbies and interests'),
        ),
    ]
