# Generated by Django 3.2 on 2022-09-28 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('socialize', '0012_auto_20220928_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialProfileBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookmark_datetime', models.DateTimeField(auto_now_add=True)),
                ('bookmarker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('social_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='socialize.socialprofile')),
            ],
        ),
        migrations.AddField(
            model_name='socialprofile',
            name='bookmarkers',
            field=models.ManyToManyField(blank=True, related_name='bookmarked_social_profiles', related_query_name='bookmarked_social_profile', through='socialize.SocialProfileBookmark', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='socialprofilebookmark',
            constraint=models.UniqueConstraint(fields=('social_profile', 'bookmarker'), name='unique_social_profile_bookmark'),
        ),
    ]
