# Generated by Django 3.2 on 2022-10-01 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialize', '0013_auto_20220928_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialprofile',
            name='birth_date',
            field=models.DateField(help_text="Please at least enter the correct birth year. <br>Your birth date and age won't be visible to other users. <br>Also, you should be at least 15 years old.", verbose_name='Birthday'),
        ),
    ]
