"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 3.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '!73!8_w-350#rrf(%z@5l5d#i%5v%sjpe%3uf+b9xc3^0zji-@'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []
AUTH_USER_MODEL = 'users.User'
SITE_NAME = 'CamerEcole'

# Application definition

INSTALLED_APPS = [
	'modeltranslation',  # this has to come before admin app to enable admin integration
	'django.contrib.admin',
	'django.contrib.auth',
	'django.contrib.contenttypes',
	'django.contrib.sessions',
	'django.contrib.messages',
	'django.contrib.staticfiles',
	'django.contrib.sites',   # added
	'django.contrib.humanize', # added

	### 3rd party ###
	# 'captcha',
	'ckeditor',
	'ckeditor_uploader',
	'crispy_forms',
	'crispy_bootstrap5',
	# 'django_elasticsearch_dsl',
	'django_extensions',
	'django_filters',
	'django_hosts',
	'debug_toolbar',
	# 'easy_thumbnails',
	# 'extra_views',
	'formtools',
	'taggit',

	# My apps
	'core',
	'hitcount',
	'marketplace',
	'users',
	'past_papers',
	'qa_site',
	'socialize',

]

MIDDLEWARE = [
	'django_hosts.middleware.HostsRequestMiddleware',  # for django_hosts
	'django.middleware.security.SecurityMiddleware',
	'django.contrib.sessions.middleware.SessionMiddleware',
	'django.middleware.locale.LocaleMiddleware',  # for translation
	'django.middleware.common.CommonMiddleware',
	'django.middleware.csrf.CsrfViewMiddleware',
	'debug_toolbar.middleware.DebugToolbarMiddleware',  # for debug_toolbar
	'django.contrib.auth.middleware.AuthenticationMiddleware',
	'django.contrib.messages.middleware.MessageMiddleware',
	'django.middleware.clickjacking.XFrameOptionsMiddleware',
	'django_hosts.middleware.HostsResponseMiddleware',  # for django_hosts
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
	{
		'BACKEND': 'django.template.backends.django.DjangoTemplates',
		'DIRS': [
			# by default, django template loader will look within each app for a 'templates' folder...
			# i.e. app_name/templates/app_name/..  (place templates here) to avoid namespace issues
			BASE_DIR / 'templates'  # enable finding templates from config/templates directory
		],
		'APP_DIRS': True,   # find templates in 'templates' directory within each app
		'OPTIONS': {
			'context_processors': [
				'django.template.context_processors.debug',
				'django.template.context_processors.request',
				'django.template.context_processors.i18n',  # for i18n.. requests will now include LANGUAGES, LANGUAGE_CODE & LANGUAGE_BIDI
				# 'django.template.context_processors.static',  # added
				'django.contrib.auth.context_processors.auth',
				'django.contrib.messages.context_processors.messages',],
		},
	},
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
	'default': {
		'ENGINE': 'django.db.backends.postgresql_psycopg2',
		'NAME': 'sitedb',
		'USER': 'sergeman',
		'PASSWORD': 'notanut',
		'HOST': 'localhost',
		'PORT': '5432',
	}
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
	{
		'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
	},
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

gettext = lambda s: s
LANGUAGES = (
	('en', gettext('English')),
	('fr', gettext('French')),
)

LOCALE_PATHS = [
	BASE_DIR / 'locale',
]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'core/static'
STATICFILES_DIRS = [
	BASE_DIR / 'static'
]

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

SITE_ID = 2
LOGIN_URL = '/users/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# This logs any emails sent to the console (e.g. so you can copy the password reset link from the console)
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
DEFAULT_FROM_EMAIL = 'webmaster@localhost'  # default email to use...

AUTHENTICATION_BACKENDS = [
	'django.contrib.auth.backends.ModelBackend',

]

DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'  # the default

### django storages ###
# DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
# STATICFILES_STORAGE = 'storages.backends.s3boto3.S3StaticStorage'
# STATICFILES_STORAGE = 'storages.backends.s3boto3.S3ManifestStaticStorage'
# AWS_ACCESS_KEY_ID = ''
# AWS_SECRET_ACCESS_KEY = ''
# AWS_STORAGE_BUCKET_NAME
# AWS_S3_FILE_OVERWRITE = False
# AWS_S3_REGION_NAME = 'eu-west-1'

### ckEditor ###
CKEDITOR_UPLOAD_PATH = 'ckuploads/'   # create a directory in media directory
CKEDITOR_IMAGE_BACKEND = 'pillow'
CKEDITOR_RESTRICT_BY_USER = True
CKEDITOR_ALLOW_NONIMAGE_FILES = False

CKEDITOR_CONFIGS = {
	'default': {
		'toolbar': 'none',
	},
	'listing_description': {
		'toolbar': 'Custom',
		'toolbar_Custom': [
			['Bold', 'Italic', 'Table'],
			['NumberedList', 'BulletedList', 'HorizontalRule'],
			['Outdent', 'Indent', '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight'],
			# '/',  # go to new line
			['Format', 'Font', 'FontSize'],
			['Maximize', 'Preview']
			# ['Maximize', 'Source', 'Preview'] TextColor
		],
		'tabSpaces': 4,
		'width': 'auto'  # this will be set to the ck-editor instance instead(id='cke_id_description' and class='cke_1 cke ... ')
		# 'uiColor': '#ff3333',
	},
	'add_question': {
		'toolbar': 'Custom',
		'toolbar_Custom': [
			['Bold', 'Italic'],
			['Link', 'Blockquote', 'Image',], # code too
			['NumberedList', 'BulletedList', 'Format', 'HorizontalRule'],
			['Outdent', 'Indent', '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight'],
			['Undo', 'Redo'],
			['Maximize', 'Preview']
		],
		'tabSpaces': 4,
		'width': 'auto' 
		# 'uiColor': '#ff3333',
	}
}


### django-crispy-forms ###
CRISPY_ALLOWED_TEMPLATE_PACKS = 'bootstrap5'
CRISPY_TEMPLATE_PACK = 'bootstrap5'
CRISPY_FAIL_SILENTLY = not DEBUG


### django_hosts ###
ROOT_HOSTCONF = 'config.hosts'
DEFAULT_HOST = 'www'


### django-taggit ###
TAGGIT_CASE_INSENSITIVE = True


### debug_toolbar ###
INTERNAL_IPS = [
	'127.0.0.1',
]

### modeltranslation ###
MODELTRANSLATION_DEFAULT_LANGUAGE = 'en'
MODELTRANSLATION_DEBUG = True
MODELTRANSLATION_FALLBACK_LANGUAGES = ('fr', 'en')



