# Generated by Django 3.1.3 on 2021-10-17 22:43

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('content_en', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('content_fr', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('posted_datetime', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('original_language', models.CharField(choices=[('en', 'English'), ('fr', 'French')], editable=False, max_length=2)),
                ('update_language', models.CharField(blank=True, choices=[('en', 'English'), ('fr', 'French')], editable=False, max_length=2)),
            ],
            options={
                'verbose_name': 'Academic Question Answer',
                'verbose_name_plural': 'Academic Question Answers',
            },
        ),
        migrations.CreateModel(
            name='AcademicAnswerComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted_datetime', models.DateTimeField(auto_now_add=True)),
                ('content', ckeditor.fields.RichTextField(verbose_name='Content')),
                ('content_en', ckeditor.fields.RichTextField(null=True, verbose_name='Content')),
                ('content_fr', ckeditor.fields.RichTextField(null=True, verbose_name='Content')),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('original_language', models.CharField(choices=[('en', 'English'), ('fr', 'French')], editable=False, max_length=2)),
            ],
            options={
                'verbose_name': 'Academic Answer Comment',
                'verbose_name_plural': 'Academic Answer Comments',
            },
        ),
        migrations.CreateModel(
            name='AcademicQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted_datetime', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('original_language', models.CharField(choices=[('en', 'English'), ('fr', 'French')], editable=False, max_length=2)),
                ('update_language', models.CharField(blank=True, choices=[('en', 'English'), ('fr', 'French')], editable=False, max_length=2)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('title_en', models.CharField(max_length=150, null=True, verbose_name='Title')),
                ('title_fr', models.CharField(max_length=150, null=True, verbose_name='Title')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Content')),
                ('content_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Content')),
                ('content_fr', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Content')),
                ('slug', models.SlugField(max_length=250)),
                ('slug_en', models.SlugField(max_length=250, null=True)),
                ('slug_fr', models.SlugField(max_length=250, null=True)),
            ],
            options={
                'verbose_name': 'Academic Question',
                'verbose_name_plural': 'Academic Questions',
                'ordering': ['-posted_datetime'],
            },
        ),
        migrations.CreateModel(
            name='AcademicQuestionComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted_datetime', models.DateTimeField(auto_now_add=True)),
                ('content', ckeditor.fields.RichTextField(verbose_name='Content')),
                ('content_en', ckeditor.fields.RichTextField(null=True, verbose_name='Content')),
                ('content_fr', ckeditor.fields.RichTextField(null=True, verbose_name='Content')),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('original_language', models.CharField(choices=[('en', 'English'), ('fr', 'French')], editable=False, max_length=2)),
            ],
            options={
                'verbose_name': 'Academic Question Comment',
                'verbose_name_plural': 'Academic Question Comments',
            },
        ),
        migrations.CreateModel(
            name='AcademicQuestionTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Name')),
                ('name_en', models.CharField(max_length=20, null=True, unique=True, verbose_name='Name')),
                ('name_fr', models.CharField(max_length=20, null=True, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('slug_en', models.SlugField(max_length=100, null=True, unique=True)),
                ('slug_fr', models.SlugField(max_length=100, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Academic Question Tag',
                'verbose_name_plural': 'Academic Question Tags',
            },
        ),
        migrations.CreateModel(
            name='SchoolAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('content_en', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('content_fr', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('posted_datetime', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('original_language', models.CharField(choices=[('en', 'English'), ('fr', 'French')], editable=False, max_length=2)),
                ('update_language', models.CharField(blank=True, choices=[('en', 'English'), ('fr', 'French')], editable=False, max_length=2)),
            ],
            options={
                'verbose_name': 'School Question Answer',
                'verbose_name_plural': 'School Question Answers',
            },
        ),
        migrations.CreateModel(
            name='SchoolAnswerComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted_datetime', models.DateTimeField(auto_now_add=True)),
                ('content', ckeditor.fields.RichTextField(verbose_name='Content')),
                ('content_en', ckeditor.fields.RichTextField(null=True, verbose_name='Content')),
                ('content_fr', ckeditor.fields.RichTextField(null=True, verbose_name='Content')),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('original_language', models.CharField(choices=[('en', 'English'), ('fr', 'French')], editable=False, max_length=2)),
            ],
            options={
                'verbose_name': 'School Answer Comment',
                'verbose_name_plural': 'School Answer Comments',
            },
        ),
        migrations.CreateModel(
            name='SchoolQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted_datetime', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('original_language', models.CharField(choices=[('en', 'English'), ('fr', 'French')], editable=False, max_length=2)),
                ('update_language', models.CharField(blank=True, choices=[('en', 'English'), ('fr', 'French')], editable=False, max_length=2)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('content_en', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('content_fr', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
            ],
            options={
                'verbose_name': 'School Question',
                'verbose_name_plural': 'School Questions',
                'ordering': ['-posted_datetime'],
            },
        ),
        migrations.CreateModel(
            name='SchoolQuestionComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted_datetime', models.DateTimeField(auto_now_add=True)),
                ('content', ckeditor.fields.RichTextField(verbose_name='Content')),
                ('content_en', ckeditor.fields.RichTextField(null=True, verbose_name='Content')),
                ('content_fr', ckeditor.fields.RichTextField(null=True, verbose_name='Content')),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('original_language', models.CharField(choices=[('en', 'English'), ('fr', 'French')], editable=False, max_length=2)),
            ],
            options={
                'verbose_name': 'School Question Comment',
                'verbose_name_plural': 'School Question Comments',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Name')),
                ('name_en', models.CharField(max_length=30, null=True, unique=True, verbose_name='Name')),
                ('name_fr', models.CharField(max_length=30, null=True, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(max_length=200)),
                ('slug_en', models.SlugField(max_length=200, null=True)),
                ('slug_fr', models.SlugField(max_length=200, null=True)),
                ('datetime_added', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaggedAcademicQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qa_site.academicquestion')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_questions', to='qa_site.academicquestiontag')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
