# Generated by Django 3.1.3 on 2021-10-17 22:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
        ('qa_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolquestioncomment',
            name='poster',
            field=models.ForeignKey(on_delete=models.SET(users.models.get_dummy_user), related_name='school_question_comments', related_query_name='school_question_comment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schoolquestioncomment',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', related_query_name='comment', to='qa_site.schoolquestion'),
        ),
        migrations.AddField(
            model_name='schoolquestioncomment',
            name='upvoters',
            field=models.ManyToManyField(blank=True, related_name='upvoted_school_question_comments', related_query_name='upvoted_school_question_comment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schoolquestioncomment',
            name='users_mentioned',
            field=models.ManyToManyField(blank=True, related_name='_schoolquestioncomment_users_mentioned_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schoolquestion',
            name='bookmarkers',
            field=models.ManyToManyField(blank=True, related_name='bookmarked_school_questions', related_query_name='bookmarked_school_question', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schoolquestion',
            name='downvoters',
            field=models.ManyToManyField(blank=True, related_name='downvoted_school_questions', related_query_name='downvoted_school_question', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schoolquestion',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='following_school_questions', related_query_name='following_school_question', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schoolquestion',
            name='poster',
            field=models.ForeignKey(on_delete=models.SET(users.models.get_dummy_user), related_name='school_questions', related_query_name='school_question', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schoolquestion',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', related_query_name='question', to='core.institution'),
        ),
        migrations.AddField(
            model_name='schoolquestion',
            name='upvoters',
            field=models.ManyToManyField(blank=True, related_name='upvoted_school_questions', related_query_name='upvoted_school_question', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schoolanswercomment',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', related_query_name='comment', to='qa_site.schoolanswer'),
        ),
        migrations.AddField(
            model_name='schoolanswercomment',
            name='poster',
            field=models.ForeignKey(on_delete=models.SET(users.models.get_dummy_user), related_name='school_answer_comments', related_query_name='school_answer_comment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schoolanswercomment',
            name='upvoters',
            field=models.ManyToManyField(blank=True, related_name='upvoted_school_answer_comments', related_query_name='upvoted_school_answer_comment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schoolanswercomment',
            name='users_mentioned',
            field=models.ManyToManyField(blank=True, related_name='_schoolanswercomment_users_mentioned_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schoolanswer',
            name='downvoters',
            field=models.ManyToManyField(blank=True, related_name='downvoted_school_answers', related_query_name='downvoted_school_answer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schoolanswer',
            name='poster',
            field=models.ForeignKey(on_delete=models.SET(users.models.get_dummy_user), related_name='school_answers', related_query_name='school_answer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schoolanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', related_query_name='answer', to='qa_site.schoolquestion'),
        ),
        migrations.AddField(
            model_name='schoolanswer',
            name='upvoters',
            field=models.ManyToManyField(blank=True, related_name='upvoted_school_answers', related_query_name='upvoted_school_answer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='academicquestioncomment',
            name='poster',
            field=models.ForeignKey(on_delete=models.SET(users.models.get_dummy_user), related_name='academic_question_comments', related_query_name='academic_question_comment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='academicquestioncomment',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', related_query_name='comment', to='qa_site.academicquestion'),
        ),
        migrations.AddField(
            model_name='academicquestioncomment',
            name='upvoters',
            field=models.ManyToManyField(blank=True, related_name='upvoted_academic_question_comments', related_query_name='upvoted_academic_question_comment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='academicquestioncomment',
            name='users_mentioned',
            field=models.ManyToManyField(blank=True, related_name='_academicquestioncomment_users_mentioned_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='academicquestion',
            name='bookmarkers',
            field=models.ManyToManyField(blank=True, related_name='bookmarked_academic_questions', related_query_name='bookmarked_academic_question', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='academicquestion',
            name='downvoters',
            field=models.ManyToManyField(blank=True, related_name='downvoted_academic_questions', related_query_name='downvoted_academic_question', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='academicquestion',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='following_academic_questions', related_query_name='following_academic_question', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='academicquestion',
            name='poster',
            field=models.ForeignKey(on_delete=models.SET(users.models.get_dummy_user), related_name='academic_questions', related_query_name='academic_question', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='academicquestion',
            name='subject',
            field=models.ForeignKey(blank=True, help_text='Allow this field empty if your subject is not present.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='academic_questions', related_query_name='academic_question', to='qa_site.subject', verbose_name='Subject'),
        ),
        migrations.AddField(
            model_name='academicquestion',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='qa_site.TaggedAcademicQuestion', to='qa_site.AcademicQuestionTag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='academicquestion',
            name='upvoters',
            field=models.ManyToManyField(blank=True, related_name='upvoted_academic_questions', related_query_name='upvoted_academic_question', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='academicanswercomment',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', related_query_name='comment', to='qa_site.academicanswer'),
        ),
        migrations.AddField(
            model_name='academicanswercomment',
            name='poster',
            field=models.ForeignKey(on_delete=models.SET(users.models.get_dummy_user), related_name='academic_answer_comments', related_query_name='academic_answer_comment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='academicanswercomment',
            name='upvoters',
            field=models.ManyToManyField(blank=True, related_name='upvoted_academic_answer_comments', related_query_name='upvoted_academic_answer_comment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='academicanswercomment',
            name='users_mentioned',
            field=models.ManyToManyField(blank=True, related_name='_academicanswercomment_users_mentioned_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='academicanswer',
            name='downvoters',
            field=models.ManyToManyField(blank=True, related_name='downvoted_academic_answers', related_query_name='downvoted_academic_answer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='academicanswer',
            name='poster',
            field=models.ForeignKey(on_delete=models.SET(users.models.get_dummy_user), related_name='academic_answers', related_query_name='academic_answer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='academicanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', related_query_name='answer', to='qa_site.academicquestion'),
        ),
        migrations.AddField(
            model_name='academicanswer',
            name='upvoters',
            field=models.ManyToManyField(blank=True, related_name='upvoted_academic_answers', related_query_name='upvoted_academic_answer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='schoolquestion',
            index=models.Index(fields=['-posted_datetime'], name='qa_site_sch_posted__39462b_idx'),
        ),
        migrations.AddIndex(
            model_name='academicquestion',
            index=models.Index(fields=['-posted_datetime'], name='qa_site_aca_posted__2ed6b8_idx'),
        ),
    ]
