# Generated by Django 3.1.3 on 2021-11-02 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa_site', '0005_auto_20211101_0400'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicanswercomment',
            name='update_language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('fr', 'French')], editable=False, max_length=2),
        ),
        migrations.AddField(
            model_name='academicquestioncomment',
            name='update_language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('fr', 'French')], editable=False, max_length=2),
        ),
        migrations.AddField(
            model_name='schoolanswercomment',
            name='update_language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('fr', 'French')], editable=False, max_length=2),
        ),
        migrations.AddField(
            model_name='schoolquestioncomment',
            name='update_language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('fr', 'French')], editable=False, max_length=2),
        ),
    ]
