# Generated by Django 3.2 on 2022-07-26 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa_site', '0010_discussquestion_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussquestiontag',
            name='name_en',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='discussquestiontag',
            name='name_fr',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='discussquestiontag',
            name='slug_en',
            field=models.SlugField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='discussquestiontag',
            name='slug_fr',
            field=models.SlugField(max_length=100, null=True, unique=True),
        ),
    ]
