# Generated by Django 3.2 on 2022-07-26 13:05

from django.db import migrations, models
import django.db.models.deletion
import taggit_selectize.managers


class Migration(migrations.Migration):

    dependencies = [
        ('qa_site', '0011_auto_20220726_0410'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('name_en', models.CharField(max_length=50, null=True, unique=True, verbose_name='Name')),
                ('name_fr', models.CharField(max_length=50, null=True, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('slug_en', models.SlugField(max_length=100, null=True, unique=True)),
                ('slug_fr', models.SlugField(max_length=100, null=True, unique=True)),
                ('datetime_added', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Question Tag',
                'verbose_name_plural': 'Question Tags',
            },
        ),
        migrations.AlterField(
            model_name='academicquestion',
            name='tags',
            field=taggit_selectize.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='qa_site.TaggedAcademicQuestion', to='qa_site.QuestionTag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='discussquestion',
            name='tags',
            field=taggit_selectize.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='qa_site.TaggedDiscussQuestion', to='qa_site.QuestionTag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='taggedacademicquestion',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_questions', to='qa_site.questiontag'),
        ),
        migrations.AlterField(
            model_name='taggeddiscussquestion',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discuss_questions', to='qa_site.questiontag'),
        ),
        migrations.DeleteModel(
            name='AcademicQuestionTag',
        ),
        migrations.DeleteModel(
            name='DiscussQuestionTag',
        ),
    ]
