# Generated by Django 3.2 on 2022-07-26 15:10

from django.db import migrations
import qa_site.managers


class Migration(migrations.Migration):

    dependencies = [
        ('qa_site', '0012_auto_20220726_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicquestion',
            name='tags',
            field=qa_site.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='qa_site.TaggedAcademicQuestion', to='qa_site.QuestionTag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='discussquestion',
            name='tags',
            field=qa_site.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='qa_site.TaggedDiscussQuestion', to='qa_site.QuestionTag', verbose_name='Tags'),
        ),
    ]
