# Generated by Django 3.2 on 2022-08-03 02:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qa_site', '0014_alter_academicquestion_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='discusscomment',
            name='users_mentioned',
            field=models.ManyToManyField(blank=True, related_name='discuss_comments_mentioned', related_query_name='discuss_comment_mentioned', to=settings.AUTH_USER_MODEL),
        ),
    ]
