# Generated by Django 3.2 on 2022-09-23 02:18

import core.utils
from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('qa_site', '0016_auto_20220909_0200'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscussCommentPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', easy_thumbnails.fields.ThumbnailerImageField(upload_to='discuss_comments_photos/')),
                ('upload_datetime', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', related_query_name='photo', to='qa_site.discusscomment')),
            ],
            options={
                'verbose_name': 'Discussion Comment Photo',
                'verbose_name_plural': 'Discussion Comments Photos',
            },
            bases=(models.Model, core.utils.PhotoModelMixin),
        ),
        migrations.CreateModel(
            name='AcademicCommentPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', easy_thumbnails.fields.ThumbnailerImageField(upload_to='academic_comments_photos/')),
                ('upload_datetime', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', related_query_name='photo', to='qa_site.academiccomment')),
            ],
            options={
                'verbose_name': 'Academic Comment Photo',
                'verbose_name_plural': 'Academic Comments Photos',
            },
            bases=(models.Model, core.utils.PhotoModelMixin),
        ),
    ]
