# Generated by Django 3.2 on 2022-09-28 20:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qa_site', '0019_auto_20220928_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussquestion',
            name='bookmarkers',
            field=models.ManyToManyField(blank=True, related_name='bookmarked_discuss_questions', related_query_name='bookmarked_discuss_question', through='qa_site.DiscussQuestionBookmark', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='discussquestion',
            name='downvoters',
            field=models.ManyToManyField(blank=True, related_name='downvoted_discuss_questions', related_query_name='downvoted_discuss_question', through='qa_site.DiscussQuestionDownvote', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='discussquestion',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='following_discuss_questions', related_query_name='following_discuss_question', through='qa_site.DiscussQuestionFollow', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='discussquestion',
            name='upvoters',
            field=models.ManyToManyField(blank=True, related_name='upvoted_discuss_questions', related_query_name='upvoted_discuss_question', through='qa_site.DiscussQuestionUpvote', to=settings.AUTH_USER_MODEL),
        ),
    ]
