# Generated by Django 3.1.3 on 2021-09-30 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
