# Generated by Django 3.1.3 on 2021-10-17 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('name_en', models.CharField(max_length=50, null=True, unique=True, verbose_name='Name')),
                ('name_fr', models.CharField(max_length=50, null=True, unique=True, verbose_name='Name')),
                ('location', models.CharField(help_text='Street or quarter where institution is located', max_length=60, verbose_name='Location')),
                ('datetime_added', models.DateTimeField(auto_now_add=True, verbose_name='Date/time added')),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
