# Generated by Django 3.1.3 on 2021-09-27 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('G', 'General'), ('M', 'Mentions'), ('A', 'Activities'), ('F', 'Flags')], default='G', max_length=2),
        ),
    ]
