# Generated by Django 3.1.3 on 2021-09-29 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_notification_follow_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('G', 'General'), ('M', 'Mention'), ('A', 'Activity'), ('F', 'Flag'), ('FF', 'Following'), ('R', 'Reported')], default='G', max_length=2),
        ),
    ]
