# Generated by Django 3.1.3 on 2021-11-24 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20211124_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageholder',
            name='height',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imageholder',
            name='width',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
