# Generated by Django 3.1.3 on 2021-09-29 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210929_0458'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='absolved',
            field=models.BooleanField(null=True),
        ),
    ]
