# Generated by Django 3.1.3 on 2021-09-30 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_notification_absolved'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
